### ISSUE TITLE
LNK2019	unresolved external symbol nk_init_default referenced in function nk_d3d11_init

### ISSUE THREAD

**Issue by riperjack** [Immediate-Mode-UI/Nuklear#1]
Hi, I got several linker errors when trying to compile DirectX11 Demo in Visual Studio 2019. I have d3d11.lib linked. I'm using main.c from from demo/d3d11. Could someone please give me a hand with that ? 

![obraz](https://user-images.githubusercontent.com/18187926/69651176-fbcaaf00-106f-11ea-88c8-2efab00e111b.png)

**Comment by riperjack** [comment]
Ok, I managed to fix the issue. For anyone having same problem, make sure you have all the preprocessor directives defined, that are required to enable blocks of code that linker cannot find. 

In my case it was:
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING

Regarding IID_ID3D11Texture2D error:
Property project -> Configuration Properties -> Linker -> Input -> Additional Dependicies ;
Add:
d3d11.lib
d3dcompiler.lib
dxgi.lib
dxguid.lib

**Comment by dumblob** [comment]
Glad you fixed it! If you have other issues, ask again.

**Comment by KahnSoft** [comment]
Same problemes, lib can be nice compile, after use refrences linker colapse:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol NK_MEMCPY	Y:\3D\OpenGL\GLKern\NuklearLibD.lib(nuklear_draw.obj)		
Error	LNK2001	unresolved external symbol NK_MEMCPY	Y:\3D\OpenGL\GLKern\NuklearLibD.lib(nuklear_window.obj)	

Comes without any solution its very modern to use nothing of solutions, why the named solutions ?
