### ISSUE TITLE
Arc Command Support for GDI & X

### ISSUE THREAD

**Issue by dumblob** [Immediate-Mode-UI/Nuklear#106]
@Vucay would you be interested in updating your PR https://github.com/vurtun/nuklear/pull/796 to this new repository? I think arc support would be great!

**Comment by Vucay** [comment]
Sure. I'm rather busy right now but I'll look into it. Shouldn't take much work though; it's basically just a few definitions that are missing (in the new repository) at the moment.

**Comment by Vucay** [comment]
The pull request #112 is ready for review.

**Comment by RobLoach** [comment]
:fire:
