### ISSUE TITLE
demo/glfw_opengl3 Remove global state

### ISSUE THREAD

**Issue by dumblob** [Immediate-Mode-UI/Nuklear#107]
@maddouri would you be interested in updating your PR https://github.com/vurtun/nuklear/pull/760/files to this new repository? I think removal of the global state is a good idea.

**Comment by maddouri** [comment]
Thanks for your interest in the PR. IMHO, not having a global state ought to be a requirement for all code samples.
Unfortunately, I doubt that I would have enough resources to dedicate to porting https://github.com/vurtun/nuklear/pull/760 to this repo.

To anyone interested: please feel free to adapt my PR's code to this new repo :)
