### ISSUE TITLE
how do i compile one of the demo examples?

### ISSUE THREAD

**Issue by dhuux** [Immediate-Mode-UI/Nuklear#108]
I know my english is worse and my question is newbie, but, try to understand and help anyway.

I recently started learning programming starting with c as my first and i also wanted to learn c alongside with GUI programming in c by using nuklear, but the problem is i can't figure out how to compile `demo/glfw_opengl3/main.c` on `64-bit windows.`
I'm using `vscode with C/C++ extension + mingw-64  installed  with mingw-64 installer.`
As for `glew` and `glfw 64-bit` i copied their files to these folders:

```
Project
    main.c
    Makefile
    Nuklear_glfw_gl3.h
```

```
  MinGW-64
      +- mingw32     
            +- i686-w64-mingw32
                      +- include
                        |  +- GLFW
                        |    |  glfw3.h
                        |    |  glfw3native.h
                        |  +- GL (for glew)
                        |       eglew.h
                        |       glew.h
                        |       glxew.h
                        |       wglew.h
                        |
                      +- lib (for glfw+glew)
                           libglfw3.a
                           libglfw3dll.a
                           glfw3.dll ( to system32)
                           glew32.lib
                           glew32s.lib
                           glew32.dll ( to system32)
```
tried with `gcc -o main.exe main.c -lglfw3 -lopengl32 -lglew32 -lkernel32 -luser32 -lgdi32`
And throws a long list of `undefined reference to ` errors starting with `_imp____glewCreateProgram`

i tried `make -f makefile`
it creates empty `bin` and` -p` folders and complains
![20200410_212954](https://user-images.githubusercontent.com/63465816/79013997-a3a1ce80-7b72-11ea-8991-28b918145240.jpg)

I really don't even know what i'm doing, but, if you help me to get the window, i will keep playing with it.

I know, but, i'm not starting with python/javascript first and i'm not going to wait till i learn c and get used to programming world. i want to do this.

**Comment by dumblob** [comment]
Hi @dhuux, it's great you're learning C "the hard way". Let's star with some basics.

1. Can you compile on your machine the demos and/or examples included in this repository without any special adjustments/settings? This is the most important first step.

**Comment by Hejsil** [comment]
The [`gdi`](https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/gdi) backend is probably the easiest to get compiling on Windows. I'll recommend starting there, and see if you can compile that.

**Comment by dhuux** [comment]
Thanks @dumblob.

> some of the demos and/or examples (not necessarily the GL* backends) included in this repository

like which bro? Are there examples with no backends in this ripo?

> without any special adjustments/settings? 

you mean i don't need to install glew and glfw, put their files into GLFW/GL dirs respectively to get rid of glew/glfw header files missing complaints like _`make -f example/makefile`_ ?

It seems that i need some sort of step by step guide, like how do compile?

**Comment by dhuux** [comment]
thanks @Hejsil.

if It's possible for me to get these three things working safe and sound on my system. I want to try this, so can you show me or at least guide me to a tutorial on this?

Like how do you compile `demo/glfw_opengl3/main.c` successfully?

I need to use:
- `glfw` as windowing and I/O lib.
- `opengl3/4` as backend to learn some graphics programming along the way before switching to vulkan.
- `glew` as opengl loading extension.

i want to be quite familiar with setting-up these properly with (not microsoft visual studio) vs code or normal code editors by the time i'm ready to program real GUIs.

**Comment by dhuux** [comment]
> The gdi backend is probably the easiest to get compiling on Windows. I'll recommend starting there, and see if you can compile that.

@Hejsil, I will probably try this, although i prefer to spend time on this.

**Comment by Hejsil** [comment]
@dhuux sorry, I don't develop on windows, so I can't be of too much help on this. I also don't have a windows machine on me right now to work with, so that doesn't help.

**Comment by dhuux** [comment]
@Hejsil, it's okay.
do you think this will be strightforward on linux if create bootable arch linux on USB drive?

**Comment by Hejsil** [comment]
I use `arch` myself, and I've just confirmed that if you install the `glfw` package through `pacman` you can just run the make files in the demoes for `glfw_opengl2/3/4` and it should just work.

**Comment by Hejsil** [comment]
Also, for windows, you might be able to look up some generic tutorial for compiling a simple hello world program with `glfw` and `opengl` using `minGW`. If you get that working then using nuklear from there should be easy (I hope).

**Comment by dhuux** [comment]
@Hejsil, thanks for the help.

> glfw package through pacman.

i will absolutely do this, as soon as i get home. `pacman` is really a godsend

> some generic tutorial for compiling a simple hello world program with glfw and opengl using minGW.

It sounds this is the only way to go about it. I'm targeting windows, because, everyone here in my country uses windows, so i don't know if i will be able to apply what i learned from linux to windows later.

Thanks again.

**Comment by Hejsil** [comment]
Sounds like you have been unblocked. I'll close this issue. If you have any other questions you can just ask them here.

**Comment by dhuux** [comment]
fair enough.

**Comment by dumblob** [comment]
I'm a bit late to the party, but for a Windows workflow I'd recommend something like (didn't test it as I don't have any Windows machine at hand):

1. open terminal from the standard Windows startup menu (or alternatively open *Run* from the start menu, write `cmd.exe` and press Enter)
2. `cd C:\users\...\arbitrary_directory`
3. `git clone --depth 1 https://github.com/Immediate-Mode-UI/Nuklear.git`
4. `cd Nuklear\demo\gdi\`
5. `build.bat`

If this goes well, then we could try the same with GL* backends and see how to do that (all backends except for Direct3D and GDI based backends lack windows `build.bat` script, so there'll be some hand work required as the bundled `Makefile`s are not always written with Windows in mind).

What is the motivation to use GL* backends? If you won't use any other graphics library than Nuklear, then your code can be written in a backend-independent manner thus allowing you to switch backends in compile time based on the target platform.

**Comment by im-fin** [comment]
how tf u run makefile on windows
