### ISSUE TITLE
Compile issues with strict C++17

### ISSUE THREAD

**Issue by Nielsbishere** [Immediate-Mode-UI/Nuklear#11]
Strict C++17 (all warnings as errors), doesn't allow if with a constexpr expression in there. That's what `if constexpr` is for. This is an easy fix; only define the nk_memcpy & nk_memset implementations if they are used. I did it by adding a `NK_DEF_MEMCPY` and `NK_DEF_MEMSET` if the user didn't define theirs. And the check for if(sizeof(nk_draw_index)==2) should only happen ifndef NK_UINT_DRAW_INDEX. 
https://github.com/Nielsbishere/Nuklear/commit/d0c22ebf09e5b72c502b4e88da2d88c474f189c4
The branch above fixes it, but I don't know where those are located in the actual source (only the nuklear.h is modified).

**Comment by dumblob** [comment]
`grep -Er 'define NK_MEMSET' src/` is my friend :wink::
```
src/nuklear_internal.h:#define NK_MEMSET nk_memset
```

```
master 0$ grep -Er 'NK_UINT_DRAW_INDEX' src/
src/nuklear.h:#ifdef NK_UINT_DRAW_INDEX
src/HEADER:/// NK_UINT_DRAW_INDEX              | Defining this will set the size of vertex index elements when using NK_VERTEX_BUFFER_OUTPUT to 32bit instead of the default of 16bit
src/HEADER:///     - NK_UINT_DRAW_INDEX
```

```
master 0$ grep -Er 'nk_memcopy' src/
src/nuklear_internal.h:#define NK_MEMCPY nk_memcopy
src/nuklear_internal.h:NK_LIB void* nk_memcopy(void *dst, const void *src, nk_size n);
src/nuklear_util.c:nk_memcopy(void *dst0, const void *src0, nk_size length)
```

**Comment by dumblob** [comment]
Btw. why not use directly `#ifdef NK_MEMSET` directly and introduce another "chained" define `#ifdef NK_DEF_MEMCPY`?

**Comment by Nielsbishere** [comment]
The point is that there's a few checks like this:
`if(sizeof(nk_draw_index) > 2)` which in c++17 with /Wall /Werr doesn't compile since it should be constexpr. This expression can be done by a simple ifdef, because it is only larger if it's defined as an int. I myself replace memcpy and memset by std::memcpy and std::memset, so it shouldn't even try to compile those IMO.
