### ISSUE TITLE
"Documentation" in readme is a dead link

### ISSUE THREAD

**Issue by brah** [Immediate-Mode-UI/Nuklear#114]
[doc link](https://cdn.statically.io/gh/Immediate-Mode-UI/nuklear/master/doc/nuklear.html)

`400 Bad Request. The user is not registered with the HTML service. To enable the service please contact https://twitter.com/staticallyio`

also instead of opening a new issue for two minor issues:
is there a way to have the nuklear window movable without using the windows frame? I'm using nuklear for a very light login system so it's not a major problem, it's more quality of life. Just curious is all :)
see gif - (with `NK_WINDOW_MOVABLE` begin flag: https://i.imgur.com/wQG0t0q.gifv

**Comment by dumblob** [comment]
>`400 Bad Request. The user is not registered with the HTML service. To enable the service please contact https://twitter.com/staticallyio`

Thanks for pointing it out - PRs or any other contribution activity welcome!

>is there a way to have the nuklear window movable without using the windows frame?

I'd say so (didn't look it up though) - don't hesitate and look at the Nuklear source as it's pretty self-explanatory and hackable :wink: (reading the source is the best way to use single header libs after all).

**Comment by dumblob** [comment]
>is there a way to have the nuklear window movable without using the windows frame?

Or maybe I misunderstood - the gif seems to move a "Nuklear window" (i.e. not the window of your window_manager/shell). So which which "windows frame" are you referring to?

**Comment by dylanmit** [comment]
> Or maybe I misunderstood - the gif seems to move a "Nuklear window" (i.e. not the window of your window_manager/shell). So which which "windows frame" are you referring to?

Sorry if it was a poor example gif - see: https://i.imgur.com/rBf52ek.gifv
I hide that windows "frame" using `WS_POPUP` when I call `CreateWindowExW`
see:
 `HWND wnd = CreateWindowExW(0, wc.lpszClassName, wc.lpszClassName, WS_VISIBLE | WS_POPUP, horizontal, vertical, rect.right - rect.left, rect.bottom - rect.top, nullptr, nullptr, wc.hInstance, nullptr);
`

**Comment by dumblob** [comment]
Ok, with "windows frame" you mean the "frame drawn by the Microsoft Windows [`CreateWindowExW()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexw ) function", right?

And you would want to additionally hide the frame which Nuklear draws for Nuklear windows (i.e. hide the frame containing the white window title text including the darker blueish background), right?

Then yeah, just look at the Nuklear source code and in a minute you have it solved :wink: (I strongly encourage you to read the source as you might better understand also other things which'll make your Nuklear life easier in the future :wink:).

**Comment by RobLoach** [comment]
Looks like the link was fixed. Thanks!
