### ISSUE TITLE
Demos for the pictures shown on the home page [question]

### ISSUE THREAD

**Issue by aganm** [Immediate-Mode-UI/Nuklear#116]
There's a couple pictures on the home page showing what nuklear can do. One of them a battlefield themed settings menu.

Could someone provide demos for these picture demos? I'm trying to learn nuklear but the documentation alone is not quite so obvious. The current demos can be useful but they do not have most of the picture demos on the home page.

Thanks

**Comment by dumblob** [comment]
This might help https://github.com/vurtun/nuklear/issues/733 (back then Nuklear was called Zahnrad).
