### ISSUE TITLE
Use string.h ?

### ISSUE THREAD

**Issue by Temtaime** [Immediate-Mode-UI/Nuklear#117]
Why this header is not used?
Custom implementations of memcpy, memset, strlen and other functions just make the library larger and slower. 
Can we get rid of them and use string.h?

**Comment by Hejsil** [comment]
You'll notice, if you read a little deeper into the code, that Nuklear actually doesn't include anything from C's standard library unless asked. This is because Nuklear wants to be completely self contained. This as some major benefits:

* Allows other languages to call into Nuklear without then having to pull in the libc dependency if they don't need it.
* Allows Nuklear to run on everything that has a C compiler (even if no libc is available).

Now, we could have an option that tells Nuklear to use the functions from libc. `NK_INCLUDE_FIXED_TYPES` already exists afterall.

**Comment by Temtaime** [comment]
You are accepting PR's to make it compilable for C++17, but cannot go with ancient libc? This library is present on all the systems and almost all the languages use it.
If "anything" has C compiler without libc, then "anything" doesn't have C compiler.
IMO avoiding libc is a major loss.

**Comment by dumblob** [comment]
>If "anything" has C compiler without libc, then "anything" doesn't have C compiler.

That's actually quite far from reality. In embedded development one doesn't have any libc, but just HW-oriented SDK or just documentation (MCU registers etc.) and a half-functional C compiler. Nowadays many such embedded setups have small color display to display some stuff (icons, buttons, simple widgets, some text, but quite few).

So far you mentioned one reason why you'd like to get rid of related code in `nuklear.h` - its size (I'm deliberately skipping the statement that it makes the library slower as you can use libc if you want with just one define). I can guarantee that removing them would help by very few percent of the overall size of `nuklear.h`. From our experience these implementations didn't cause any issues so far (there were no bugs found to my knowledge and no other maintenance of the code was needed).

If you really care that much about the size, you're free to use a tool like [unifdef](https://github.com/fanf2/unifdef ).

To wrap up I still do not understand the motivation behind your request. Could you elaborate?

**Comment by Temtaime** [comment]
This library is barely suitable for embedded development.
Nuklear uses floats every now and then, so it forcefully requires FPU or FPU emulation which is costly.
Also it's size is big, so it's not suitable for MCUs, and much bigger than libc for those MCUs.
Can you show me a compiler that doesn't have memcpy in its libc? Almost every compiler has some intrinsic for its libc functions and can optimize them.
So it's not only about code size, but also about performance.
For instance a quote from the docs:
>nuklear will use its own slow and not highly accurate version.

IMO nuklear should keep it's codebase clean and use the capabilities provided by C99 compiler.
It will perform better in all the ways then.
Just don't reinvent the square wheel.

**Comment by Hejsil** [comment]
You can override all these function to use the libc version if you so desire. This should ifdef out Nuklears own implementation, therefor not adding any size to the binary (if this doesn't work, then there is a bug in Nuklear that needs fixing). So I don't quite see the problem. You have all the tools you need to make Nuklear do what you want here.

My usecase for having these implementations in Nuklear is in fact to not pull in libc. I'm using the  [`Zig`](https://ziglang.org/) programming language, which does not depend on libc in any way. Forcing me to link against libc would actually be a waist. On some systems I would have to make my programs dynamically linked, just for a few small functions, which is not worth it at all.

**Comment by Temtaime** [comment]
Anyway it is a good thing to use libc by default allowing other users to exclude it.
If my opinion is wrong then feel free to close this issue

**Comment by RobLoach** [comment]
There are some string functions in `nuklear_string.c` that are not provided by string.h, including some utf8 stuffs. Would be nice to allow overriding them, but certainly not a requirement. Thanks Temtaime!

If you'd like a `NK_STRING_OVERRIDES` defines or something, feel free to create a new issue :+1:
