### ISSUE TITLE
Padding is not correctly figured for the bottom of a window

### ISSUE THREAD

**Issue by ronaaron** [Immediate-Mode-UI/Nuklear#132]
Setting padding to, say, {20,20} works fine on the left, top, and right.  But if you then do nk_window_get_content_region(), you'll find that the height is 40 too high (e.g. 2 times the top padding).

I assume this is an error...

**Comment by ronaaron** [comment]
Anyone?

**Comment by Hejsil** [comment]
I'm not sure I understand. The title talks about bottom padding, but the issue describes a wrong height. Do you have some example code that show what is going on?

**Comment by ronaaron** [comment]
If you set the style padding for the window, nk_window_get_bounds() or nk_window_get_content_region() return a rectangle which is **bigger** than the window, by twice the y padding.

**Comment by ronaaron** [comment]
by "bigger' I mean "taller". The width is correct.

**Comment by Hejsil** [comment]
Thanks, that makes more sense. I've reproduced the bug with this small snipped of code in the x11 demo:
```
ctx->style.window.padding.x = 50;
ctx->style.window.padding.y = 50;
if (nk_begin(ctx, "Demo", nk_rect(50, 50, 200, 200), NK_WINDOW_BORDER))
{
    struct nk_rect rect = nk_window_get_content_region(ctx);
    printf("%f %f\n", rect.w, rect.h);
}
nk_end(ctx);
```

```
...
86,000000 186,000000
...
```

Seems that the height is pinned at 186, never changing no matter what the padding is.

**Comment by ronaaron** [comment]
So in my routine which calls the nk routine, I just subtract twice "style.window.padding.y" and it looks ok.

**Comment by Hejsil** [comment]
Yea, I'm working on a patch that basically does this in the right place. I'm hitting a small issue in a demo that I'm investigating.
