### ISSUE TITLE
OpenGL texture image issue

### ISSUE THREAD

**Issue by yaoz39** [Immediate-Mode-UI/Nuklear#133]
Try to display OpenGL texture in the window using glfw_gl2.  The simple test code is attached.  I expected the display to be in red.  Instead it shows a gray scale image.

[tex.txt](https://github.com/Immediate-Mode-UI/Nuklear/files/4630181/tex.txt)

**Comment by yaoz39** [comment]
I figured out what the problem is.  For nk_draw_image(), the color parameter needs to be nk_rgb(255, 255, 255) in order to show the image.

**Comment by dumblob** [comment]
@yaoz39 glad to hear you've solved it! Btw. it would make sense to document this (e.g. at the top of the source code file) - feel free to make a PR :wink:.
