### ISSUE TITLE
Version tracking?

### ISSUE THREAD

**Issue by oxr463** [Immediate-Mode-UI/Nuklear#136]
There are no tags or releases. How can I install a specific version of this library?

**Comment by dumblob** [comment]
Unfortunately you'll need to check out each historical commit and look for version number either in `src/CHANGELOG` or `package.json`.

PRs are highly welcome (there was an ongoing effort to automate our release management, but I can't find it right now in all the PRs and Issues).

**Comment by oxr463** [comment]
Interesting. So typically, even with a change log or a `package.json` file, we would still use git tags or even GitHub Releases so that we can easily download specific versions.

Let me fork and show you what I mean.

**Comment by oxr463** [comment]
Okay, here is an example tag, https://github.com/oxr463/Nuklear/releases/tag/v4.02.4

If you wish to apply it to the main branch, you can follow these commands:

```sh
git remote add oxr463-fork https://github.com/oxr463/Nuklear.git
git pull --all # pulls in the tag(s)
git tag -l # list the tag(s)
git push --tags # seems self explanatory
```
Each release needs a tag. Not sure if someone wants to go back and tag each one, or if we just want to start tagging on each release moving forward.

# Reference:

- https://git-scm.com/book/en/v2/Git-Basics-Tagging
- https://help.github.com/en/github/administering-a-repository/about-releases

**Comment by dumblob** [comment]
I see at least 2 things here:
1. we need to decide when to tag (shall we do it for each `.patch` bump? or just for `.minor`? or even somehow for backends & demos (e.g. through some additional hash to the existing semver - I wouldn't want to start versioning our backends&demos as we do not require them to have such quality as `nuklear.h` library itself)?)
2. this has to be automated (e.g. part of our `paq` scripts etc. - including "safety" measures to allow for removal of temporary tags if any etc.) or it has to be well-described in `Readme.md` under [Reviewers guide](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide )

Btw. I prefer the automated method e.g. with `paq`, but feel free to make PR and we'll discuss the details there.

**Comment by dumblob** [comment]
@Hejsil thoughts?

**Comment by oxr463** [comment]
> 1. we need to decide when to tag

You should tag each time the version changes in your `package.json` file.

> 2. ...or it has to be well-described in Readme.md under Reviewers guide.

It is simple enough to add a step here that says how to do it.

Here are two simple ways to tag:

1. Using git:

```sh
git tag v4.02.5
git push --tags
```

Note: this assumes you have updated your `package.json` file already.

2. Using GitHub Releases: <https://github.com/oxr463/Nuklear/releases/new>

**Comment by dumblob** [comment]
Our release management is already a bit hairy and this would further worsen the situation - I'd rather encourage others to write code than follow our long manuals how to submit a proper PR.

That's why I'd prefer automation (which needs to handle changes in PR - e.g. if already tagged and later some additional stuff will come and the version changes in between due to other merges, then the older tag in that PR has to be removed etc.).

Let's hear what @Hejsil and others think.

**Comment by Hejsil** [comment]
I agree with @dumblob that this should be automatic. People tend to not get a PR right in the first go, and adding more steps will just add to the list of things people have to do when contributing. I don't think we can afford any more manual steps. I wonder if we can just have a CI step that runs when `package.json` :thinking: 

I have no strong opinion otherwise. I personally would just git checkout at a specific commit if I needed a certain version, but I can understand having these releases so that downloading a specific version is as simple as clicking a button.

**Comment by oxr463** [comment]
You can run the git command to tag on change to that `package.json` file. Let me submit a PR.

**Comment by dane-johnson** [comment]
I would add that not having versioned releases makes this really hard to package, which is a shame as I would like to add it to the AUR.

**Comment by dumblob** [comment]
@dane-johnson please do not confuse release tracking (i.e. releases under the link *Releases* on GitHub) and release versioning. Of course we have versioned releases - just look at `package.json` and `src/CHANGELOG` (there is also the plan to add Nuklear to https://github.com/clibs/clib/wiki/Packages#program-flow ).

So you can definitely package it everywhere very easily.

We're looking for new contributors (there are no NDAs, no covenants, no codes of conduct). Release tracking, addition to clib repo, etc. that's something we need to fully automate (the release process in our [Reviewer's guide](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide ) is already a bit tedious). Feel free to help us out :wink:.

**Comment by dane-johnson** [comment]
Not having GitHub releases makes it hard to find the source for a specific version. Say I want to get version "4.01.5". I have to search through the commit history for when the package.json line says "4.01.5" and then curl "https://github.com/Immediate-Mode-UI/Nuklear/archive/1cdd4f10aa8f2669657b4ab49068f43cd063a9d0.tar.gz", whereas if there was a GitHub release I would just curl "https://github.com/Immediate-Mode-UI/Nuklear/archive/v4.01.5.tar.gz" and be sure that is the correct version.

**Comment by dumblob** [comment]
>Not having GitHub releases makes it hard to find the source for a specific version.

Of course, that's a different story than "not having versioned releases" :wink:. Feel free to make a PR automating it all (preferably including addition of release tags to all older commits :wink:).

**Comment by epsilon-0** [comment]
Is there any progress on this currently?
I am packaging this for gentoo and would really appreciate if there are github tags.

Thanks,
Aisha

**Comment by yurivict** [comment]
Is it too difficult to maintain GitHub tags manually until an automated solution is developed?
I think most projects just tag manually.
