### ISSUE TITLE
Remove Symbol Space from Combo

### ISSUE THREAD

**Issue by zgcrowno** [Immediate-Mode-UI/Nuklear#141]
Sorry if this is a trivial matter, but I've spent all day trying to *completely* remove symbols from my Nuklear combo boxes to no avail. I can of course set these symbols' types to NK_SYMBOL_NONE in order to remove their images, but the *space* they occupy remains the same, resulting in the combo boxes' text being unable to fill up the combo's entire width. Is there any way to fill a combo's entire width with text? Thanks in advance!

**Comment by dumblob** [comment]
That's a good question. I don't know of anyone trying to achieve the same. But feel free to look at the Nuklear source code as it's pretty hackable and then make a PR :wink:. I'm quite busy in these times, so I can't take a deeper look now :cry:.

**Comment by zgcrowno** [comment]
No worries. Thanks for getting back to me so quickly!

I'll poke around a bit, and if I come up with a decent solution I'll make a PR.
