### ISSUE TITLE
Newline Character Support for nk_text/nk_label/etc.

### ISSUE THREAD

**Issue by zgcrowno** [Immediate-Mode-UI/Nuklear#148]
In working with the library, I've noticed that Nuklear text functions like nk_text and nk_label don't seem to recognize/enforce newlines when encountering special strings like "\n" or "\r". I decided to research this, and found that an issue and PR were opened for the old Vurtun library ([#532](https://github.com/vurtun/nuklear/issues/532) and [#661](https://github.com/vurtun/nuklear/pull/661)). Is this something you all are looking into at the moment? If not, I could probably try my hand at integrating it with a PR of my own.

**Comment by dumblob** [comment]
I'm also not working on this, but as you already found out, it's a known issue and any PRs are thus very much welcome.

**Comment by zgcrowno** [comment]
Alright, well I'll hopefully be able to start looking into this over the next couple of weeks! I'll close this issue out and hopefully make a PR addressing it soon.

**Comment by IgorAlexey** [comment]
I believe that this should be reopened
