### ISSUE TITLE
pool->pages invalid causing read access violation

### ISSUE THREAD

**Issue by AlEscher** [Immediate-Mode-UI/Nuklear#154]
For the past couple of days I've been trying to move from DearImGui to Nuklear (I'm in cpp).  
I've overcome a lot of problems during this transition but I can't figure this one out and hope someone can help me.  
  
I'm (trying) to render in a hooked EndScene using D3D9.  
I use the provided nuklear_d3d9.h for initialization:  
This function gets called once.
```
bool Menu::InitNuklear()  
{
        int img_width = 600;
	int img_height = 600;
	ctx = *nk_d3d9_init(pDevice, img_width, img_height);
	{nk_font_atlas* atlas;
	nk_d3d9_font_stash_begin(&atlas);
	nk_font* droid = nk_font_atlas_add_default(atlas, 12, 0);
	nk_d3d9_font_stash_end();
	nk_style_set_font(&ctx, &droid->handle); }
	return true;
}
```

This gets called once per frame:
```
void Menu::RenderNuklear()
{
	static nk_colorf bg;
	bg.r = 0.10f, bg.g = 0.18f, bg.b = 0.24f, bg.a = 1.0f;

	if (nk_begin(&ctx, "Demo", nk_rect(50, 50, 230, 250),
		NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_SCALABLE |
		NK_WINDOW_MINIMIZABLE | NK_WINDOW_TITLE))
	{
		enum { EASY, HARD };
		static int op = EASY;
		static int property = 20;

		nk_layout_row_static(&ctx, 30, 80, 1);
		if (nk_button_label(&ctx, "button"))
			fprintf(stdout, "button pressed\n");
		nk_layout_row_dynamic(&ctx, 30, 2);
		if (nk_option_label(&ctx, "easy", op == EASY)) op = EASY;
		if (nk_option_label(&ctx, "hard", op == HARD)) op = HARD;
		nk_layout_row_dynamic(&ctx, 22, 1);
		nk_property_int(&ctx, "Compression:", 0, &property, 100, 10, 1);

		nk_layout_row_dynamic(&ctx, 20, 1);
		nk_label(&ctx, "background:", NK_TEXT_LEFT);
		nk_layout_row_dynamic(&ctx, 25, 1);
		if (nk_combo_begin_color(&ctx, nk_rgb_cf(bg), nk_vec2(nk_widget_width(&ctx), 400))) {
			nk_layout_row_dynamic(&ctx, 120, 1);
			bg = nk_color_picker(&ctx, bg, NK_RGBA);
			nk_layout_row_dynamic(&ctx, 25, 1);
			bg.r = nk_propertyf(&ctx, "#R:", 0, bg.r, 1.0f, 0.01f, 0.005f);
			bg.g = nk_propertyf(&ctx, "#G:", 0, bg.g, 1.0f, 0.01f, 0.005f);
			bg.b = nk_propertyf(&ctx, "#B:", 0, bg.b, 1.0f, 0.01f, 0.005f);
			bg.a = nk_propertyf(&ctx, "#A:", 0, bg.a, 1.0f, 0.01f, 0.005f);
			nk_combo_end(&ctx);
		}
	}
	nk_end(&ctx);
	nk_d3d9_render(NK_ANTI_ALIASING_ON);
	nk_clear(&ctx); // If I don't call this (again) after nk_d3d9_render, NK_ASSERT(win->seq != ctx->seq); fails
}
```  
I've tried to mimic what demo/d3d9/main.c does, except I don't need to create a window and already have a valid `IDirect3DDevice9* pDevice`
My problem is that it crashes on the first nk_begin call, more specifically:  
![image](https://user-images.githubusercontent.com/50444010/85202925-4365a080-b30a-11ea-8f60-81edd949d487.png)
Here is the exact location:  
![NuklearCrash](https://user-images.githubusercontent.com/50444010/85202833-7e1b0900-b309-11ea-9e38-d9010551da44.PNG)  
I am unsure about why this is happening, I assumed nuklear_d3d9.h takes care of all initialization steps, or is there something I'm missing?  
All I'm trying to do for now is to render the demo window.

**Comment by dumblob** [comment]
Sorry for not coming earlier to you. Have you solved this somehow?

**Comment by AlEscher** [comment]
> Sorry for not coming earlier to you. Have you solved this somehow?

Hi,  
No, unfortunately I didn't manage to solve it.  
I have abandoned this approach and have switched to another GUI framework.

**Comment by dumblob** [comment]
>No, unfortunately I didn't manage to solve it.

You wrote you've tried to run the demo `demo/d3d9/main.c` which should be a question of a double click on [`build.bat`](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/d3d9/build.bat ) in that folder. If this didn't work for you, could you help us and post the output errors you got so that we can fix it?

After this demo runs flawlessly, we can proceed to the `pool->pages` issue which is quite unexpected as we didn't have any such severe memory-related issues for few years already.

>I have abandoned this approach and have switched to another GUI framework.

I feel sorry we couldn't help you out earlier (we're busy people, but would very much like to help).

Just out of curiosity, may I ask which GUI framework you've switched to?

**Comment by AlEscher** [comment]
> You wrote you've tried to run the demo `demo/d3d9/main.c` which should be a question of a double click on [`build.bat`](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/d3d9/build.bat) in that folder.

That's not what I meant. I tried to compile the main.c using the build file and compiling manually, both didn't work (with the build.bat file nothing would happen, compiling manually would throw unresolved imports errors but I didn't really look into it). What I meant was that I did what the main.c file does (or at least I tried to) with some minor changes to fit my use case (not creating a window and a render device, but instead passing my already valid (and working) device to `nk_d3d9_init`  
Maybe it's my fault and I messed something up, I posted all the code that I used in my original post.  

> I feel sorry we couldn't help you out earlier (we're busy people, but would very much like to help).

I understand that, it's no problem.

> Just out of curiosity, may I ask which GUI framework you've switched to?  

I decided to switch to a much smaller framework: [FGui](https://github.com/otvv/fgui) 
A few weeks ago I started with [DearImGui](https://github.com/ocornut/imgui) but I came to find out that there aren't many  
options to customize the look and design of the menu (except of course changing things in the DearImGui source code, but I was afraid to mess with it since it is a pretty huge framework). I looked for alternatives and found Nuklear. I liked the look and design of the showcases.  
Don't get me wrong, this GUI is pretty good but I think it just doesn't fit my particular use case.  
The FGui code is much smaller so I can have a better overview and change and customize things without having to worry about breaking something, since I actually understand how FGui works. But this just comes down to me not being very experienced.  
Also I don't have a need for all the memory management options that Nuklear provides, which where somewhat confusing for me in the beginning. I see how these options could be important for other people (and obviously they are given the amount of stars that the old repo and this one have), I guess it was just too advanced for me ^^

**Comment by dumblob** [comment]
@AlEscher aaah, ok, that's understandable. Feel free to come back later if you'll need something a bit more "advanced" (this is relative - many consider Nuklear rather "basic" than "advanced" :wink:).

The reason why `demo/d3d9/main.c ` didn't work for you (using `build.bat` in that folder) will stay an open question to investigate for now (though I think I'll leave this topic closed).

**Comment by AlEscher** [comment]
> @AlEscher aaah, ok, that's understandable. Feel free to come back later if you'll need something a bit more "advanced" (this is relative - many consider Nuklear rather "basic" than "advanced" 😉).

Understandable. When I say advanced I particularly mean large, at least for me it is.
> The reason why `demo/d3d9/main.c ` didn't work for you (using `build.bat` in that folder) will stay an open question to investigate for now (though I think I'll leave this topic closed).

I looked into that again and managed to compile the demo window (with the build.bat file)  
As expected, I was the problem since I didn't read the remark in the build file about using Visual Studio 2015.  
I use Visual Studio 2019 Community Edition, so changing:  
`call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86`  
to  
`call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86`  
worked and I was able to compile and open the demo window. All demo features seemed to be working,  
so I assume I messed something up while trying to port the main.c to my own implementation.  
Maybe adding a build.bat file for different Visual Studio versions could prove helpful? (Although I accept that it was my fault for not reading the remark)

**Comment by dumblob** [comment]
I'm glad it's just about the version. Instead of providing just one folder, we might consider using a wildcard (for a demo it doesn't matter which compiler will be used) in a for loop (with `goto :eof` as break after first iteration). Feel free to make a PR or I'll get back to this hopefully later.
