### ISSUE TITLE
"File" (childless) node in nk_tree

### ISSUE THREAD

**Issue by Nielsbishere** [Immediate-Mode-UI/Nuklear#159]
Below is an example of my file explorer:
![File explorer](https://user-images.githubusercontent.com/28758736/86597016-7317d800-bf9b-11ea-9f5a-bc7fb63db329.png)

Like assumed; the files ending with "spv"or "ttf" are actually files. These shouldn't have dropdowns.
How would I go around doing that? Do I have to set the image to something else for that to be fixed?

**Comment by exchg** [comment]
You can extend `enum nk_collapse_states` by adding new state (something like NK_EMPTY) and handle it inside  `static int state_base()`

**Comment by Nielsbishere** [comment]
Thanks, I'll get on it with my new PR

**Comment by exchg** [comment]
Or maybe even better to extend `enum nk_tree_type` not `enum nk_collapse_states`

**Comment by Nielsbishere** [comment]
![finished](https://user-images.githubusercontent.com/28758736/86609178-dad61f00-bfab-11ea-8867-f9b805144c01.png)
I'll make a PR for this and all other things I made a pull for before.

**Comment by Nielsbishere** [comment]
https://github.com/Immediate-Mode-UI/Nuklear/pull/160 works well on my branch :+1: Thanks
