### ISSUE TITLE
d3d12 demo?

### ISSUE THREAD

**Issue by jaysan1627** [Immediate-Mode-UI/Nuklear#161]
Are you planning to do a d3d12 demo any time soon?
Thanks!

**Comment by dumblob** [comment]
IIRC there was an ongoing effort - feel free to search this tracker and mainly pull requests through. If you won't find exact answers, please reopen this issue :wink:.

**Comment by dumblob** [comment]
FYI we've just merged a D3D12 backend demo from @Ohjurot . Feel free to test it and improve it if you find some rough edges!
