### ISSUE TITLE
Hide/Remove this window

### ISSUE THREAD

**Issue by a1987zz** [Immediate-Mode-UI/Nuklear#162]
The question is: How can I hide/remove this window, so that there is just a Nuklear window GDI++.
![687474703a2f2f692e696d6775722e636f6d2f666d43797a494b2e706e67](https://user-images.githubusercontent.com/25912664/87239353-da5bdf00-c416-11ea-9dd5-2c54821c57fe.png)
I understand that the Nuklear window is written on top of other windows through winapi. I tried using HWND wnd = GetDesktopWindow () and
HWND FindWindow in line: `ctx = nk_gdip_init (wnd, WINDOW_WIDTH, WINDOW_HEIGHT);` other windows, but to no avail. Only works with CreateWindowExW. And so the question is: is there any way to hide or remove this window so that Nuklear works without auxiliary windows. Thank!

**Comment by hongshui3000** [comment]
**DWORD style = WS_POPUP;** 
wnd = CreateWindowExW(exstyle, wc.lpszClassName, L"Nuklear Demo",
        style | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT,
        rect.right - rect.left, rect.bottom - rect.top,
        NULL, NULL, wc.hInstance, NULL);

**Comment by RobLoach** [comment]
Sounds like more Windows API or GDI work rather than Nuklear scope. Looks like hong had a good suggestion. Thanks!
