### ISSUE TITLE
request: SDL opengl4 example

### ISSUE THREAD

**Issue by aganm** [Immediate-Mode-UI/Nuklear#174]
I tried the SDL opengl3 example with opengl3 and it works, but I need opengl4 features and when I try to use it, it crashes on the opengl program creation.

Could someone make an opengl4 example? Thanks

**Comment by dumblob** [comment]
I'll leave this open so that someone can pick it up. Currently we're out of time and we're focusing on a [major rework of buffer/string handling](https://github.com/Immediate-Mode-UI/Nuklear/pull/81 ) to allow better interoperation with other languages than C/C++.

**Comment by aganm** [comment]
@dumblob  oh, it turns out my crash was due to another issue, it actually works with opengl4! Could be nice to have an opengl4 version, but yeah, the issue was on my side.

**Comment by dumblob** [comment]
If it works with opengl4 without modifications, could you make a PR with `sdl_opengl4` directory with just one file (ideally `Makefile`) with `printf "refer to sdl_opengl3, it's 100% compatible\n"`?

**Comment by aganm** [comment]
@dumblob I made a pull request. #184
