### ISSUE TITLE
Backend: SDL2+Vulkan

### ISSUE THREAD

**Issue by cesss** [Immediate-Mode-UI/Nuklear#175]
I was wondering if anybody wrote such a backend.

**Comment by Badgerthwart** [comment]
This is a pretty good starting point. It doesn't seem to handle textures beyond the font texture, but it should get you up and running:
https://github.com/m0ppers/nuklear-glfw-vulkan

**Comment by dumblob** [comment]
@Badgerthwart thanks for the pointer!

@m0ppers willing to make a PR? We'll happily merge your backend and give you commit permissions to this repository if you'd like to participate on development in general (especially review PRs dealing with `nuklear.h` itself).

**Comment by m0ppers** [comment]
@dumblob thanks for reaching out. unfortunately I have too many side projects already :(

**Comment by dumblob** [comment]
Understood. Yeah, reviewing is time consuming. Still, if you'd find few minutes for the PR (as you understand the code the best), that'd be great :wink:.

**Comment by aheirman** [comment]
Hey, since I've used this, nuklear-glfw-vulkan, and had to make some modifications to make it usable in a ('real') application, I could upstream my work. I do have very little experience with nuklear. How would you like it the most as a demo like with opengl or part of the main src? Because it is far more code than the little opengl wrappers(nuklear_sdl_glX.h).

**Comment by dumblob** [comment]
We'd prefer it to be a "demo" (i.e. a new backend). Feel free to structure the backend in a way it's readable. Preferably though as a single file (.h) or two files (.c .h) to ease adoption by end users. And don't worry, reviews for backends are not as strict as for `nuklear.h` itself :wink:.

**Comment by cesss** [comment]
I'm very interested on this, @aheirman !!

**Comment by WatIsDeze** [comment]
> 
> 
> Hey, since I've used this, nuklear-glfw-vulkan, and had to make some modifications to make it usable in a ('real') application, I could upstream my work. I do have very little experience with nuklear. How would you like it the most as a demo like with opengl or part of the main src? Because it is far more code than the little opengl wrappers(nuklear_sdl_glX.h).

yes please, pass it on!

**Comment by riri** [comment]
Now Glfw+vulkan backend is integrated in demos with #583, doing an SDL2+vulkan should be easier :)
