### ISSUE TITLE
Use Toggle

### ISSUE THREAD

**Issue by Cube0001OnDiscord** [Immediate-Mode-UI/Nuklear#177]
hey i was unable to figure out how to use toggle thing 
![Capture](https://user-images.githubusercontent.com/68885041/89991722-be489900-dc73-11ea-8485-5872475953b6.PNG)

**Comment by RobLoach** [comment]
What could you not figure out for it? Perhaps use a checkbox widget instead? Feel free to re-open if you're still having an issue.
