### ISSUE TITLE
font and max_memory error

### ISSUE THREAD

**Issue by CODESOLE** [Immediate-Mode-UI/Nuklear#180]

**Comment by dumblob** [comment]
I hope you solved your problem. If not, please post more details and reopen this issue, thanks!

**Comment by CODESOLE** [comment]
No actually i can not solve. I wonder does this library require any  third party API like SFML, SDL etc. to create OS window and then inside create nuklear ui or can nuklear just itself  create OS window and draw ui because when  #define NK_IMPLEMENTATION  and copy paste example code from README file still gives error in MAX_MEMORY and font due to  parameters don't declared. I can handle MAX_MEMORY by writing buffer 1024*1024 but in font cannot. If i compile demo  file which is SFML for example it compiles without error and runs correctly. However nuklear itself doesnt compile. So shortly can nuklear create window and draw ui inside of it with example code from README or do we have to create window with SDL, x11, SFML and then create ui with nuklear?

**Comment by dumblob** [comment]
>So shortly can nuklear create window and draw ui inside of it with example code from README or do we have to create window with SDL, x11, SFML and then create ui with nuklear?

You have to create the os window "on your own". There are though many "demos" how to do that with different configurations (e.g. SDL, X11, SFML, etc.).

**Comment by CODESOLE** [comment]
Sorry my goal is not bother you but so what's the point of example code in the README file. It doesn't work out of the box. Doesn't this misleading for new comers like me because you have to setup some library to work with it. When new comers read documents, they think that whole nuklear is self contained and example code works out of the box. Thanks for your replies btw :)  I will close issue after your answer. Thanks in advance!

**Comment by dumblob** [comment]
>Sorry my goal is not bother you but so what's the point of example code in the README file. It doesn't work out of the box.

The point is to show what one needs to write as **new code** (in other UI libs you have to write more and on top of that click around in some layout manager for a while).

For a fully compilable example, please head to `examples/` directory. The `examples/` directory though has already chosen some of our rendering backends (these backends reside in `demo/` directory) and if you don't have a matching platform it won't compile out of the box (you'd need to switch backends manually before).

The whole point of Nuklear is exactly that one can (has to) choose a backend (see `demo/` directory for their current list) unlike many (most?) other UI libraries where there is a fixed number of supported backends and if your platform of choice doesn't happen to be in this fixed list, you're most probably screwed for 10 or more years. In this regard our `examples/` directory represents what other UI libraries do, but for Nuklear it's just an example and not "the only way of using Nuklear", but quite the opposite.

I hope this clarified the situation. Feel free to ask more.
