### ISSUE TITLE
Question: how can I tell a window to automatically resize on content

### ISSUE THREAD

**Issue by aganm** [Immediate-Mode-UI/Nuklear#182]
I would like to set a window to size (0,0), and as I add widgets to it, this window should grow to contain all of its children without scrolling.

How can I do that?

**Comment by dumblob** [comment]
Did you try different flags? Which window do you mean actually? The os window or Nuklear "internal" windows? Do you have any fully working compilable example to have us take a look?

**Comment by aganm** [comment]
It's in regards to putting nuklear widgets on a row.

For example

```
float height = 30.f;
float width = 40.f;
nk_layout_row_static(ctx, height, width, 2);
nk_label(ctx, "hello world");
```

The problem is that the width of the cell is fixed to 40. If the label "hello world" is longer than 40, it will be cropped. If the label is shorter than 40, there will be empty space.

How do I make a row that changes the size of the cell automatically to fit its content?

I want to stack widgets horizontally.

**Comment by dumblob** [comment]
>I want to stack widgets of different width horizontally.

Hm, why do you use `nk_layout_row_static()` then? The `_static` suffix is for fixed width and nothing dynamic. Btw. there were similar questions in this (or the [old tracker](https://github.com/vurtun/nuklear/issues/ )), so feel free to look them up to find some more details.
