### ISSUE TITLE
Proposal: change int to _Bool

### ISSUE THREAD

**Issue by aganm** [Immediate-Mode-UI/Nuklear#183]
Would you agree with changing int types to  _Bool where appropriate?

I think it would make the API easier to use because it differentiates between ints that are used as boolean and ints that are used as actual integer.

Or, for backwards compatibility, using a ```nk_bool``` type which defines to either _Bool if C99 or int if C89.

I find myself having to lookup the documentation everytime to find out whether an int is a number or a boolean.

**Comment by dumblob** [comment]
>Or, for backwards compatibility, using a nk_bool type which defines to either _Bool if C99 or int if C89.

Backwards compatibility is a must. Overall I think this makes sense, so feel free to make a PR. Beware though, that the PR shall also be 100% compatible (as in "drop in replacement usage is the major goal") with modern C standards (it must not produce any compilation warning etc.).

**Comment by aganm** [comment]
Made the change #185
