### ISSUE TITLE
Has this been tested on Windows 10?

### ISSUE THREAD

**Issue by ghost** [Immediate-Mode-UI/Nuklear#191]
I am using Windows 10 and TDM GCC. I used the example provided here to write a program. But the program doesn't work. Nothing happens when I run the program. Below is the code. Please let me know if I am doing something wrong.

```
#define NK_IMPLEMENTATION
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#include "nuklear.h"

int main(void)
{
    enum {EASY, HARD};
    static int op = EASY;
    static float value = 0.6f;
    static int i =  20;
    struct nk_context ctx;

    struct nk_font_atlas atlas;
    struct nk_font* font = NULL;
    void* img = NULL;
    int width = 10;
    int height = 10;
    nk_font_atlas_init_default(&atlas);
    nk_font_atlas_begin(&atlas);
    font = nk_font_atlas_add_default(&atlas, 13.0f, 0);
    img = nk_font_atlas_bake(&atlas, &width, &height, NK_FONT_ATLAS_RGBA32);
    nk_font_atlas_end(&atlas, font->texture, 0);
    
    //nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);
    nk_init_default(&ctx, &(font->handle));
    //if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220), NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_CLOSABLE)) {
    nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220), NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_CLOSABLE);
        // fixed widget pixel width
        nk_layout_row_static(&ctx, 30, 80, 1);
        if (nk_button_label(&ctx, "button")) {
            // event handling
        }
        // fixed widget window ratio width
        nk_layout_row_dynamic(&ctx, 30, 2);
        if (nk_option_label(&ctx, "easy", op == EASY)) op = EASY;
        if (nk_option_label(&ctx, "hard", op == HARD)) op = HARD;
        // custom widget pixel width
        nk_layout_row_begin(&ctx, NK_STATIC, 30, 2);
        {
            nk_layout_row_push(&ctx, 50);
            nk_label(&ctx, "Volume:", NK_TEXT_LEFT);
            nk_layout_row_push(&ctx, 110);
            nk_slider_float(&ctx, 0, &value, 1.0f, 0.1f);
        }
        nk_layout_row_end(&ctx);
    //}
    //nk_font_atlas_clear(&atlas);
    //nk_end(&ctx);
} // end of main
```

**Comment by dumblob** [comment]
Nuklear is highly multiplatform and thus strongly separates rendering backend from the UI code. In your example you're missing a backend for Windows 10 - you can choose from several from the directory `demo/` (https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo ).

Feel free to close this issue if this solved your issue.

**Comment by amit0523** [comment]
Oh, ok. It was not mentioned that I need a backend too. As mentioned in this project (single header file), I thought that nuklear.h was enough.

**Comment by urcien** [comment]
>As mentioned in this project (single header file), I thought that nuklear.h was enough.

Technically it is still single header as we don't assume any backend to be part of Nuklear (you can just export the computed list of rectangles and "instructions" and bitmaps precisely describing the UI without rendering it - and some people do e.g. if they have their own 3D engines).

Though I agree, that most people won't write their backend nor export the list of instructions for further processing but rather need to build a conventional UI for conventional platforms :wink:. Feel free to make a PR to correct this (e.g. in Readme.md).

**Comment by RobLoach** [comment]
:+1:
