### ISSUE TITLE
Doc does not tell teach me Nuklear properly.

### ISSUE THREAD

**Issue by HypeByte** [Immediate-Mode-UI/Nuklear#194]
I want to learn this great GUI library, but the doc is very confusing. It is not even telling me the data types that Nuklear uses. There is a lot of information the Doc doesn't tell you about, like fonts and the datatypes. Is there a good starter doc for Nuklear, that gives me a basic introduction, and tells me about all the types and functions?

**Comment by dumblob** [comment]
Hi and thanks for your interest!

Nuklear builds upon the idea of well documented source code and encourages users to read the source as the primary documentation. Note though, that Nuklear is an [immediate mode GUI](https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics) ) library and has nearly no specific data types and that it sticks to plain C data types for nearly everything unlike [retained mode GUIs](https://en.wikipedia.org/wiki/Retained_mode ) which have many different data types powering their widgets.

**Comment by HypeByte** [comment]
Its too confusing I don't know where to start.

**Comment by dumblob** [comment]
Take one of the `demo/` backends and you won't need to read Nuklear source. There are also slightly more complex `example/`s.

**Comment by Jamesthe1** [comment]
I've been looking into the source code of `nuklear.h` and found some generally nifty documentation about what each part does. Also, the `.c` files in the include folder are mostly portions of the header file and have a label as to what they contain, so it should make finding what you want easier.

The demo files also can give better insight on how to get started; there's a lot of render "flavors" in there

**Comment by RobLoach** [comment]
Here's a bunch of docs: https://immediate-mode-ui.github.io/Nuklear/doc/index.html

But I'd bet the best place to check it out is in the demos folder, as mentioned. Getting started with SDL may be a good path forwards. Raylib is another good option for beginners.
