### ISSUE TITLE
Too hard to learn.

### ISSUE THREAD

**Issue by HypeByte** [Immediate-Mode-UI/Nuklear#195]
Please make a proper doc that explains all the data types, and explains all the functions properly. Your docs are very imperfect. We can't read the whole source just to understand how to use your library. Please give us a good doc that explains the data structs and what they are used for. The source and doc is too hard. This library woud be good if you gave us a good doc. I don't know where to learn this. I scrolled to the source, but there is nothing for me to understand from it.

**Comment by dumblob** [comment]
Take one of the `demo/` backends and you won't need to read Nuklear source. There are also slightly more complex `example/`s.

There is basically nothing to learn - just take the demo and add your own logic.

**Comment by HypeByte** [comment]
Still confusing. So many datatypes I don't even know. You guys should remake the docs so that they explain it like the audience has just seen the repo, and that they don't want to read the source.

**Comment by HypeByte** [comment]
Everyone just wants a simple library.

**Comment by HypeByte** [comment]
Reading the source is not something that the github authors should be making the audience do, just to use a project. Thats why we have docs and wikis.

**Comment by HypeByte** [comment]
If you guys did that, thousands of people would get your library.

**Comment by HypeByte** [comment]
The library seems very easy to use, but your not telling us it.

**Comment by crazyBaboon** [comment]
There is a youtube tutorial on Nuklear

**Comment by KDahir247** [comment]
exactly as crazyBaboon.
It look intimidating at first even when I was using the library, but it is actually quite easy. The best way that I've learnt Nuklear was to run main.c on one of the demo and apply it to your code.

**Comment by RobLoach** [comment]
Check the documentation too, has some good examples: https://immediate-mode-ui.github.io/Nuklear/doc/
