### ISSUE TITLE
issue with stb_rect_pack.h

### ISSUE THREAD

**Issue by chriscamacho** [Immediate-Mode-UI/Nuklear#209]
I'm linking against another library that includes stb_rect_pack.h

At the moment it looks like all or part of stb_rect_pack.h is directly pasted into nuklear

would it be possible to include it instead and add a define that will only include the required function prototypes

this way nuklear can link to the functions already included in the othe lib I'm using

for the time being I have simply commented out a handful of functions, but this is not ideal if I want to track changes with nuklear

here's the less than ideal ~~bodge~~ patch I'm using...

    --- nuklear.h	2020-10-18 21:06:20.466002835 +0100
    +++ include/nuklear.h	2020-10-18 21:03:31.513003990 +0100
    @@ -10819,7 +10819,7 @@
     {
        STBRP__INIT_skyline = 1
     };
    -
    +/*
     STBRP_DEF void stbrp_setup_heuristic(stbrp_context *context, int heuristic)
     {
        switch (context->init_mode) {
    @@ -10835,19 +10835,22 @@
     STBRP_DEF void stbrp_setup_allow_out_of_mem(stbrp_context *context, int allow_out_of_mem)
     {
        if (allow_out_of_mem)
    +*/
           /*  if it's ok to run out of memory, then don't bother aligning them; */
           /*  this gives better packing, but may fail due to OOM (even though */
           /*  the rectangles easily fit). @TODO a smarter approach would be to only */
           /*  quantize once we've hit OOM, then we could get rid of this parameter. */
    +/*
           context->align = 1;
        else {
    +*/
           /*  if it's not ok to run out of memory, then quantize the widths */
           /*  so that num_nodes is always enough nodes. */
           /*  */
           /*  I.e. num_nodes * align >= width */
           /*                   align >= width / num_nodes */
           /*                   align = ceil(width/num_nodes) */
    -
    +/*
           context->align = (context->width + context->num_nodes-1) / context->num_nodes;
        }
     }
    @@ -10870,8 +10873,9 @@
        context->height = height;
        context->num_nodes = num_nodes;
        stbrp_setup_allow_out_of_mem(context, 0);
    -
    +*/
        /*  node 0 is the full width, node 1 is the sentinel (lets us not store width explicitly) */
    +/*
        context->extra[0].x = 0;
        context->extra[0].y = 0;
        context->extra[0].next = &context->extra[1];
    @@ -10883,7 +10887,7 @@
     #endif
        context->extra[1].next = NULL;
     }
    -
    +*/
     /*  find minimum y position if it starts at x1 */
     static int stbrp__skyline_find_min_y(stbrp_context *c, stbrp_node *first, int x0, int width, int *pwaste)
     {
    @@ -11145,22 +11149,24 @@
     #else
     #define STBRP__MAXVAL  0xffff
     #endif
    -
    +/*
     STBRP_DEF int stbrp_pack_rects(stbrp_context *context, stbrp_rect *rects, int num_rects)
     {
        int i, all_rects_packed = 1;
    -
    +*/
        /*  we use the 'was_packed' field internally to allow sorting/unsorting */
    +/*
        for (i=0; i < num_rects; ++i) {
           rects[i].was_packed = i;
        }
    -
    +*/
        /*  sort according to heuristic */
    +/*
        STBRP_SORT(rects, num_rects, sizeof(rects[0]), rect_height_compare);
     
        for (i=0; i < num_rects; ++i) {
           if (rects[i].w == 0 || rects[i].h == 0) {
    -         rects[i].x = rects[i].y = 0;  /*  empty rect needs no space */
    +         rects[i].x = rects[i].y = 0;  //  empty rect needs no space 
           } else {
              stbrp__findresult fr = stbrp__skyline_pack_rectangle(context, rects[i].w, rects[i].h);
              if (fr.prev_link) {
    @@ -11172,19 +11178,20 @@
           }
        }
     
    -   /*  unsort */
    +   //  unsort 
        STBRP_SORT(rects, num_rects, sizeof(rects[0]), rect_original_order);
     
    -   /*  set was_packed flags and all_rects_packed status */
    +   //  set was_packed flags and all_rects_packed status 
        for (i=0; i < num_rects; ++i) {
           rects[i].was_packed = !(rects[i].x == STBRP__MAXVAL && rects[i].y == STBRP__MAXVAL);
           if (!rects[i].was_packed)
              all_rects_packed = 0;
        }
     
    -   /*  return the all_rects_packed status */
    +   // return the all_rects_packed status 
        return all_rects_packed;
     }
    +*/
     #endif
     
     /*
    @@ -21306,6 +21313,7 @@
     {
         float panel_spacing;
         float panel_space;
    +    (void)type;
     
         struct nk_vec2 spacing;

**Comment by Temtaime** [comment]
Juse define STBRP_STATIC and nuklear's version of library will be hidden

**Comment by chriscamacho** [comment]
great! thanks... I did look for something like that but must have been man-looking....
