### ISSUE TITLE
Reference images

### ISSUE THREAD

**Issue by LoganDark** [Immediate-Mode-UI/Nuklear#212]
I'm implementing a backend for Nuklear and it would be nice to have more completely-unthemed reference images to make sure that my rendering is accurate.

**Comment by RobLoach** [comment]
Like the first image in the gallery? https://github.com/Immediate-Mode-UI/Nuklear#gallery

Ther'es also a few Demos you can use too.

**Comment by LoganDark** [comment]
Ah, is that unthemed? Thanks!

**Comment by dumblob** [comment]
Yes, the first few pics are "unthemed" (theme in Nuklear means basically just changed colors). The rest of the pics are downstream-customized Nuklear :wink:.
