### ISSUE TITLE
How to compile the simple example?

### ISSUE THREAD

**Issue by ehsanghorbani190** [Immediate-Mode-UI/Nuklear#226]
Hi , i was trying to run the example provided in the description . i dont know if im doing it right or not :D , can you help me ?  im getting these errors :
![error](https://user-images.githubusercontent.com/35449522/101988871-c95b1680-3cb1-11eb-9720-7d165778e0a6.png)
and this is my code:
```
#define NK_IMPLEMENTATION
#include "nuklear.h"
#include <stdlib.h> // Added this after getting error for calloc func
int main(){
    /* init gui state */
struct nk_context ctx;
nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);

enum {EASY, HARD};
static int op = EASY;
static float value = 0.6f;
static int i =  20;

if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220),
    NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_CLOSABLE)) {
    /* fixed widget pixel width */
    nk_layout_row_static(&ctx, 30, 80, 1);
    if (nk_button_label(&ctx, "button")) {
        /* event handling */
    }

    /* fixed widget window ratio width */
    nk_layout_row_dynamic(&ctx, 30, 2);
    if (nk_option_label(&ctx, "easy", op == EASY)) op = EASY;
    if (nk_option_label(&ctx, "hard", op == HARD)) op = HARD;

    /* custom widget pixel width */
    nk_layout_row_begin(&ctx, NK_STATIC, 30, 2);
    {
        nk_layout_row_push(&ctx, 50);
        nk_label(&ctx, "Volume:", NK_TEXT_LEFT);
        nk_layout_row_push(&ctx, 110);
        nk_slider_float(&ctx, 0, &value, 1.0f, 0.1f);
    }
    nk_layout_row_end(&ctx);
}
nk_end(&ctx);
return 0;
}
```
thanks for helping me :D

**Comment by suvidh** [comment]
Even I am struggling to get it up and runnign, but have you linked all the dependencies? like opengl, glew etc.

**Comment by AndyMender** [comment]
`nk_init_fixed` assumes you want the memory buffer for nuklear to be fixed-size and `MAX_MEMORY` defines the size of that buffer. That's why the call to `calloc` (contiguous memory allocation). You can use `nk_init_default` so that nuklear will do the memory allocation for you.

However, the `font` variable is missing from the example code and it requires quite some extra work. I couldn't find it anywhere in the docs [here](https://immediate-mode-ui.github.io/Nuklear/doc/nuklear.html).

**Comment by RobLoach** [comment]
It completely depends on which backend you're using, and which demo you're compiling. Try the SDL ones, as SDL does seem to be widely used across both Linux and Windows.
