### ISSUE TITLE
Window always on top

### ISSUE THREAD

**Issue by phillvancejr** [Immediate-Mode-UI/Nuklear#23]
Hello I'm wondering if it is possible to make the main window topmost and float on top of all other application windows?

**Comment by dumblob** [comment]
All operating systems (and their respective "main" desktop envirnoments) offer such capabilities. This has though nothing to do with Nuklear. Please refer to the respective documentation for Windows, macOS, Gnome (Linux/BSD), KDE (Linux/BSD), ...

**Comment by phillvancejr** [comment]
Thank you very much for your reply
