### ISSUE TITLE
Forced to use C89?

### ISSUE THREAD

**Issue by ghost** [Immediate-Mode-UI/Nuklear#234]
Because Nuklear is made in C89 does that mean I'm forced to use C89 for any project I use nuklear with? Can I use it with a project in C99, C11 or any future version of C?

**Comment by 2asoft** [comment]
Nuklear itself does not impose any restrictions on the use of C89 in particular or any other C edition in general by consumers of the library.
If the compiler of choice compiles the C89 code from the Nuklear library correctly even when using a different C edition, there should be no issues.

Do note, however, that C99 and newer editions are not strict supersets of C89, and thus there may be (sometimes subtle) differences in behaviour when the same code is compiled as C89 vs eg C11.
This [StackOverflow question](https://stackoverflow.com/questions/41535927/compatibility-of-c89-c90-c99-and-c11) has a good discussion on the topic.

**Comment by Hejsil** [comment]
When it is stated that it is written in C89, I'm pretty sure what is actually implied here is, that an effort has been made to make it work for the C89 standard and above. So if Nuklear is using some C89 specific behavior that work differently in C90, then that is considered a bug and the code should be changed to work for both standards.

**Comment by RobLoach** [comment]
:+1:
