### ISSUE TITLE
NK_UINT_DRAW_INDEX not working for D3D11 implementation

### ISSUE THREAD

**Issue by Hecklezz** [Immediate-Mode-UI/Nuklear#236]
If I draw a tonne of things at once, I reach the limit of the maximum number of indices or vertexes of the default ushort size. However, I read that defining NK_UINT_DRAW_INDEX will increase this limit to a uint which should be way more than enough for what I need it for. 

However, if I have this define added, even when barely drawing anything for e.g. just using the nuklear demo, this happens (defined)- 
<details>
  <summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/1632632/103206973-e269f580-4948-11eb-88e1-db3ccad334f0.png)

</details>

when it should look normal like this (not defined)- 
<details>
  <summary>Click to expand</summary>
  
![image](https://user-images.githubusercontent.com/1632632/103206942-d2eaac80-4948-11eb-90af-7beec5baa08c.png)

</details>

Does anyone know how to properly fix this in the D3D11 implementation, or perhaps what I am doing wrong? 

The demo used is from here- 
https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/d3d11

Thank you.

**Comment by Hejsil** [comment]
Hi. I seems you're hitting the problem stated in [this comment](https://github.com/Immediate-Mode-UI/Nuklear/blob/5570172553ce48af8fe0513c8091f9bb04d3e0e4/src/nuklear_vertex.c#L227-L237). Specifically:
```
     * and don't forget to specify the new element size in your drawing
     * backend (OpenGL, DirectX, ...). For example in OpenGL for `glDrawElements`
     * instead of specifing `GL_UNSIGNED_SHORT` you have to define `GL_UNSIGNED_INT`.
     * Sorry for the inconvenience. */
```

**Comment by Hejsil** [comment]
Now, I cannot be 100% sure, but I think you need to fix [this line](https://github.com/Immediate-Mode-UI/Nuklear/blob/daecaaa5af124d4c7365883e12c2ad5b18760d67/demo/d3d11/nuklear_d3d11.h#L91):
```diff
-    ID3D11DeviceContext_IASetIndexBuffer(context, d3d11.index_buffer, DXGI_FORMAT_R16_UINT, 0);
+    ID3D11DeviceContext_IASetIndexBuffer(context, d3d11.index_buffer, DXGI_FORMAT_R32_UINT, 0);
```

**Comment by Hecklezz** [comment]
Hello there, thank you for the suggestion as it *almost* fixes the issue, but I also had to increase the MAX_VERTEX_BUFFER and MAX_INDEX_BUFFER (MAX_INDEX_BUFFER being MAX_VERTEX_BUFFER / 4) to a much larger number. Now it is able to render an ungodly amount of things without any problems what-so-ever.

Thank you!

**Comment by Hejsil** [comment]
@Hecklezz Cool. Would you be willing to open a PR that adds the changes required for this to work on the demo?

**Comment by Hecklezz** [comment]
Isn't the default ushort the intended default behavior though?

**Comment by Hejsil** [comment]
Yes, but I was thinking of having some ifdefs on `NK_UINT_DRAW_INDEX` and have the old thing if it is not defined, and do this fix if it is.

**Comment by Hecklezz** [comment]
What do you think is an appropriate MAX_VERTEX_BUFFER and MAX_INDEX_BUFFER size as the default for when using uint instead of ushort for the draw index?

**Comment by Hejsil** [comment]
Hmm, good question. The current values are already 2x/4x larger than ushort max. Idk what you're drawing and if it is a realistic workload, but I would probably leave those as is.

**Comment by Hecklezz** [comment]
What I was drawing was just testing extreme unrealistic cases, and if left to draw "everything" instead of things that were culled, or too far away, etc. So alright, I guess it can be left as they currently are.

**Comment by Hecklezz** [comment]
Do you think something like this will suffice- 

```
NK_API void nk_d3d11_render(ID3D11DeviceContext* context, enum nk_anti_aliasing AA) {
    const float blend_factor[4] = {0.0f, 0.0f, 0.0f, 0.0f};
    const UINT stride = sizeof(struct nk_d3d11_vertex);
    const UINT offset = 0;
#ifdef NK_UINT_DRAW_INDEX
    DXGI_FORMAT index_buffer_format = DXGI_FORMAT_R32_UINT;
#else
    DXGI_FORMAT index_buffer_format = DXGI_FORMAT_R16_UINT;
#endif

    context->IASetInputLayout(d3d11.input_layout);
    context->IASetVertexBuffers(0, 1, &d3d11.vertex_buffer, &stride, &offset);
    context->IASetIndexBuffer(d3d11.index_buffer, index_buffer_format, 0);
    context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
```

**Comment by Hejsil** [comment]
Yea, that seems good to me

**Comment by Hecklezz** [comment]
I should not add NK_UINT_DRAW_INDEX to the demo though right? Leave that up to the end-user to add themselves?

**Comment by Hejsil** [comment]
Correct

**Comment by Hecklezz** [comment]
Thanks again!
