### ISSUE TITLE
Suggestion: Obfuscated version of nk_edit_string

### ISSUE THREAD

**Issue by Jamesthe1** [Immediate-Mode-UI/Nuklear#245]
I've chosen this UI for my project which requires a user to sign in. However, to prevent over-the-shoulder stuff or if I'm recording how to use my app, I'd definitely like to keep the password input hidden.

**Comment by RobLoach** [comment]
There's a demo in overview...
``` c
nk_label(ctx, "Password:", NK_TEXT_LEFT);
{
    int i = 0;
    int old_len = text_len[8];
    char buffer[64];
    for (i = 0; i < text_len[8]; ++i) buffer[i] = '*';
    nk_edit_string(ctx, NK_EDIT_FIELD, buffer, &text_len[8], 64, nk_filter_default);
    if (old_len < text_len[8])
        memcpy(&text[8][old_len], &buffer[old_len], (nk_size)(text_len[8] - old_len));
}
```

**Comment by quadroli** [comment]
@RobLoach do you mind explaining how this works .. I've looked at it but its not quite clicking

**Comment by quadroli** [comment]
Never mind fahm, I got it

**Comment by quadroli** [comment]
However I do concur having a dedicated widget for this would be handy

**Comment by RobLoach** [comment]
Glad you got it working. It could live in a nuklear_extras repo or something. Certainly many advanced uses of some of these widgets :+1:

**Comment by quadroli** [comment]
Small/big issue, but, this method of obfuscating only seems to work for ASCII characters, but non-ascii like `£` will result in junk being copied as well

**Comment by quadroli** [comment]
This could be a locale issue

**Comment by quadroli** [comment]
Digging deeper, turns out '£' is a multi character constant
so, `password[i] = '*'` gives two (**) instead of one (*) when `password[i] = '£'`

**Comment by RobLoach** [comment]
When making the temporary buffer, you would need to calculate the memory size of the string, rather than its length.

**Comment by quadroli** [comment]
Is the temporary buffer `buffer` or `text[8][old_len]`
Also, I'm rather confused on how to do that (calculating the memory size of a string)
