### ISSUE TITLE
FPS not limited

### ISSUE THREAD

**Issue by VegaDeftwing** [Immediate-Mode-UI/Nuklear#246]
![nuklearfps](https://user-images.githubusercontent.com/11283620/104639394-fdd54000-566c-11eb-835b-71508a834b80.png)

This issue appears to be affecting other programs as well. [This Issue for VCV Rack](https://github.com/VCVRack/Rack/issues/1829) shows the same problem for example.

Using [LibStrangle](https://gitlab.com/torkel104/libstrangle) appears to fix the problem, but this definitely isn't optimal.

Based on the VCV issue, it seems to be affecting both Nvidia and AMD based systems, but I think it's rather rare.

**Comment by RobLoach** [comment]
Is there an issue with it not being limited?

**Comment by VegaDeftwing** [comment]
Yes. Rendering at this high of a frame rate puts extreme load on the GPU and cause kernel panics

**Comment by dumblob** [comment]
FPS limiting is in full control of the chosen backend (Nuklear itself can not do anything about it). But it's dead easy to put a sleep into the mainloop (ideally with some dynamic adjustment to compensate for sudden performance drops).

**Comment by RobLoach** [comment]
Seems out of scope for Nuklear itself, and more on the application-front. If you'd like to limit the FPS in your application, feel free to do so. The backends themselves won't implement FPS limiting within Nuklear itself. Thanks for the heads up!
