### ISSUE TITLE
Run failed: C/C++ CI - master (bacdca7)

### ISSUE THREAD

**Issue by dumblob** [Immediate-Mode-UI/Nuklear#25]
Run failed for master (bacdca7)

Repository: Immediate-Mode-UI/Nuklear
Workflow: C/C++ CI
Duration: 27.0 seconds
Finished: 2019-12-13 09:13:38 UTC

View results: https://github.com/Immediate-Mode-UI/Nuklear/commit/bacdca77720e9144b05393c722a0d2b62ced7fed/checks

Jobs:
* ca395085-040a-526b-2ce8-bdc85f692774 failed (1 annotation)

**Comment by Nielsbishere** [comment]
https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122/page/2
https://github.com/dotnet/core/issues/3995
Should work now if you rebuild it.

**Comment by Nielsbishere** [comment]
Confirmed; as https://github.com/Immediate-Mode-UI/Nuklear/pull/35 builds fine.

**Comment by AdavizeTheFirst** [comment]
Hello, I'd really love to learn Nuklear GUI. Is there any material or tutorial you could provide me with
Thanks

**Comment by dumblob** [comment]
@AdavizeTheFirst the repo was moved recently, but the [original wiki](https://github.com/vurtun/nuklear/wiki ) wasn't yet. Feel free to [move](https://github.com/darwin/move-wiki ) the original wiki (if you have any permission issues, just let me know) to this repository.

**Comment by RobLoach** [comment]
Builds passing now :wink:
