### ISSUE TITLE
Question about Nuklear project: why src folder

### ISSUE THREAD

**Issue by crazyBaboon** [Immediate-Mode-UI/Nuklear#253]
Hi,

I am sorry for polluting the issue tracker with questions about Nuklear (ideally it should only contain issues), but i don't know where to post these questions. Here we go: 

I don't understand why the Nuklear project, which claims to be contained in a single header file, maintains a **src** folder with .c files that appear to be a copy of the contents already found in Nuklear.h.

What is the purpose of the **src** folder?

Thanks!

**Comment by LewisTehMinerz** [comment]
Nuklear isn't written in one header file. That would be practically impossible to maintain. Instead, it's maintained as separate C files that are then later built into one header file which you can embed into your project.

see: https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/build.py, https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/Readme.md

**Comment by crazyBaboon** [comment]
@LewisTehMinerz 

Thanks!
