### ISSUE TITLE
Dereferencing a NULL pointer

### ISSUE THREAD

**Issue by crazyBaboon** [Immediate-Mode-UI/Nuklear#255]
Hi,

I was playing with clang and -fsanitize=undefined, 

and found that on most **opengl** nuklear backends,  there is some pointer arithmetic going on a NULL pointer, which i think results in undefined behaviour.

For example, in nuklear_glfw_gl3.h we have inside function nk_glfw3_render():

**const nk_draw_index *offset = NULL;**

this pointer offset does not get assigned any valid address and is even passed to 
**glDrawElements(GL_TRIANGLES, (GLsizei)cmd->elem_count, GL_UNSIGNED_SHORT, offset);**
where the NULL pointer probably gets dereferenced.

The following line has got the arithmetic on a NULL pointer:
**offset += cmd->elem_count;**  

Thanks!

**Comment by wheybags** [comment]
https://www.khronos.org/opengl/wiki/GLAPI/glDrawElements
> Specifies a byte offset (cast to a pointer type) into the buffer bound to GL_ELEMENT_ARRAY_BUFFER to start reading indices from.

The last parameter is a pointer type, but is used as an integer offset. It's not a bug, opengl just has a crazy API.

**Comment by crazyBaboon** [comment]
Thanks @wheybags, 

That's weird, because in https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawElements.xhtml,

they say the last parameter

> Specifies a pointer to the location where the indices are stored.

AFAIK, the NULL pointer points to an invalid memory address, so nothing really can be stored there...

**Comment by crazyBaboon** [comment]
@wheybags 

Also interesting, things are done differently in x11_opengl2 backend, where the offset pointer gets assigned a valid address.

**Comment by crazyBaboon** [comment]
Closing this "issue" as it is probably not a real issue, just some crazy opengl API
