### ISSUE TITLE
How to get real window content size?

### ISSUE THREAD

**Issue by Temtaime** [Immediate-Mode-UI/Nuklear#259]
Hi.
I want to make a widget with height related to window's height.
I know that there's `nk_window_get_content_region_size` which returns `size`.
Then i'm trying to `nk_layout_row_dynamic(ctx, size.y, 1)` and draw a widget.
But a scrollbar appears. If i substract `8` from `size.y` everything is ok. From where comes this `8`?
Thanks.

**Comment by riri** [comment]
Not tried myself to test, but I suppose there is something with padding, which can be overridden locally with style push/pop

**Comment by RobLoach** [comment]
`nk_window_get_bounds` too?
