### ISSUE TITLE
[Documentation] Comparison to other GUI tools?

### ISSUE THREAD

**Issue by rubyFeedback** [Immediate-Mode-UI/Nuklear#265]
Hey there,

Just noticed this from reddit; am sad there aren't any ruby bindings so far
but I understand you can not do everything on your own.

Anyway. A few months ago I found libui which was interesting to me, e. g.
the promise that we can write something (in ruby, for example; libui has
ruby bindings) and have it work, sort of, "out of the box" on windows. (I
myself use linux, but elderly people nearby use windows, so I could write
on linux but have everything work via a GUI on windows as-is).

- Would it be possible for you to add a subsection to the main README
or a link to a document that makes comparisons to other toolkits? Libui
would be the most logical choice, but if you can, it would also be nice to
compare nuklear to qt and gtk, if only for sake of completeness. I understand
that Nuklear is not in the same niche as qt and gtk but this is simply for
people to be able to put Nuklear into an area where it would excel as
well. Thank you for reading this request.

**Comment by RobLoach** [comment]
Feel free to add a new page in the wiki? https://github.com/Immediate-Mode-UI/Nuklear/wiki
