### ISSUE TITLE
Does \demo\glfw_opengl3 work on win10?

### ISSUE THREAD

**Issue by blojkr74** [Immediate-Mode-UI/Nuklear#270]
Hi,

Has anybody managed to compile/run \demo\glfw_opengl3 under Windows 10?

I tried using MSYS2 MinGW 64-bit. After minor modifications (e.g. adding **#include <windows.h>** to the top of main.c), the compilation is successful (using make) but when i try to run the binary it says: 

`Error 65542: WGL: The driver does not appear to support OpenGL`

Which is not true, since my graphics card supports up to opengl 3.1 (I can even compile and run imgui example_glfw_opengl3).
I have the following .dlls in the .exe folder: msys-2.0.dll, glfw3.dll and glew32.dll.

Any suggestions on how to get \demo\glfw_opengl3 to compile and run on Windows 10?

Thanks!

**Comment by hbiblia** [comment]
Hello

Windows 10 Home.
64-bit MSYS2 MinGW.
NVIDIA MX150

Tested and it works.

![image](https://user-images.githubusercontent.com/1939353/111740807-c39a4180-885b-11eb-9dcf-8cc3fa9a5e1c.png)

**Comment by crazyBaboon** [comment]
Thanks!

**Comment by RobLoach** [comment]
You may need the opengl dev binaries too.
