### ISSUE TITLE
How to 'scroll' nicely?

### ISSUE THREAD

**Issue by ronaaron** [Immediate-Mode-UI/Nuklear#274]
I'm trying to create a panel displaying Markdown (formatted) and I thought using a 'group' would work. But since I am doing direct text drawing, the group doesn't help.

Has anyone a clue how best to accomplish this?

**Comment by RobLoach** [comment]
```c
nk_uint offsetx, offsety;
nk_window_get_scroll(ctx, &offsetx, &offsety);
nk_window_set_scroll(ctx, offsetx, offsety + 1);
```
