### ISSUE TITLE
Property widget gets hovered by ProgressBar

### ISSUE THREAD

**Issue by crazyBaboon** [Immediate-Mode-UI/Nuklear#276]
Hi,

I found out that when you hover the mouse over the ProgressBar, it will incorrectly trigger the hover colors of the property widget (see image attached).

I found this out when i replaced property->hover by a custom color:
```
    property->normal        = nk_style_item_color(table[NK_COLOR_PROPERTY]);
    property->hover         = nk_style_item_color(nk_rgb(0,255,0));
    property->active        = nk_style_item_color(table[NK_COLOR_PROPERTY]);
```
![Screenshot at 2021-03-17 15-23-17](https://user-images.githubusercontent.com/19549703/111493384-66a46b80-8735-11eb-9f8b-7fbaca1fe675.png)

EDIT: forgot to mention, this test was carried out using **Linux Mint** and the **glfw_opengl2** demo

**Comment by aganm** [comment]
Nice find!

**Comment by crazyBaboon** [comment]
Thanks for finding a solution!

**Comment by crazyBaboon** [comment]
I guess this issue should only be closed if the PR gets merged...
