### ISSUE TITLE
General IMGUI question

### ISSUE THREAD

**Issue by NortherL** [Immediate-Mode-UI/Nuklear#281]
Hi! 

First of all I really like what I see in this project! I really want to use it. 
I'm not coming from the games industry and basically just want to write a desktop application. 

But there is one thing I don't really understand (I'm probably being stupid and being used to Retained GUIs).

I have some external data that changes every now and then. Let's say some sort of data that arrives over a network socket. So when this data arrives I want to show the updated data in the GUI. 

Is this a good fit for IMGUIs? 

If so, are there any common ways the changes of the data is updated in the GUI? Feels like I'm getting into threads and shared data here to solve this?

**Comment by crazyBaboon** [comment]
you could define a nk_bool (or bool if you're using C99) variable to flag whether any data has been received? 

you could use this variable to let the app decide whether to update the GUI or not.

**Comment by NortherL** [comment]
Thanks @crazyBaboon!

So it's basically that easy. I'm constantly complicate things.
