### ISSUE TITLE
help / advice for adding controller support to my GUI

### ISSUE THREAD

**Issue by ITotalJustice** [Immediate-Mode-UI/Nuklear#289]
Hi! I've just started with using Nuklear. I'm looking to make a gui for my gameboy emulator. The GUI will be controller input driven, though i want support for mouse as well.

I'm not quite sure as to how i can handle dpad (also keyboard arrow keys). Atm im thinking i should query `nk_input_is_key_pressed()` to see if the UP / DOWN is pressed, then change an index value. From there is there anyway to set a specific button to be the one that's selected / hovered?

If so, then that's perfect. However im really not sure how to do this. adding a button doesnt give any ID to pair with it.

For reference, I [made a simple mock-up](https://github.com/ITotalJustice/TotalGB/pull/31#issuecomment-833554275) for testing implementing this.

Thanks in advance for any help!

**Comment by RobLoach** [comment]
Would love joypad support! Here's another discussion around that: https://github.com/Immediate-Mode-UI/Nuklear/issues/302
