### ISSUE TITLE
Searching for a correct way to interact with GUI controls

### ISSUE THREAD

**Issue by sociopart** [Immediate-Mode-UI/Nuklear#290]
Hello there!
I'm trying to integrate Nuklear to my C++ project.
After reading lots of examples I still can't figure out how to interact with GUI controls.
How to move a button there?
And what I should do (which functions I should use/create/etc.) to make GUI control creation more logical?
My goal is to do something like createButton(x,y,caption) - how to achieve this result?
I know about nk_layout_row, but it doesn't make sense in this situation at all. This function doesn't allow creating a button at specified X/Y position.
Thanks in advance!

**Comment by FrostKiwi** [comment]
> Hello there!
> I'm trying to integrate Nuklear to my C++ project.
> After reading lots of examples I still can't figure out how to interact with GUI controls.
> How to move a button there?
> And what I should do (which functions I should use/create/etc.) to make GUI control creation more logical?
> My goal is to do something like createButton(x,y,caption) - how to achieve this result?
> I know about nk_layout_row, but it doesn't make sense in this situation at all. This function doesn't allow creating a button at specified X/Y position.
> Thanks in advance!

Placements of all elements are controlled by nk_layout_xxx functions.
The default user-friendly placement style follows the concept of rows, where new elements are added left to right, top to bottom.
If you wish to be freed from this constrained, you can use the nk_layout_space_xxx API.

> 6. nk_layout_space_xxx
> Finally the most flexible API directly allows you to place widgets inside the window. The space layout API is an immediate mode API which does not support row auto repeat and directly sets position and size of a widget. Position and size hereby can be either specified as ratio of allocated space or allocated space local position and pixel size. Since this API is quite powerful there are a number of utility functions to get the available space and convert between local allocated space and screen space.

Checkout the LAYOUT section in nuklear.h [or here in the HTML doc](https://immediate-mode-ui.github.io/Nuklear/doc/nuklear.html#layouting) , for an in-depth explanation.
