### ISSUE TITLE
Beware the cursed cyrillic charater ѐ

### ISSUE THREAD

**Issue by FrostKiwi** [Immediate-Mode-UI/Nuklear#295]
Including "0x0450" in your font config causes a weird off-by-one behavior, where every Glyph that was included after unicode character ѐ becomes shifted by one character forward. This happens across all Fonts I tested and is really bizarre. Moreover, it causes crashing in really weird and inconsistent ways, once optimizations are enabled. Specifically with Clang + optimizations the program segfaults instantly when the first text is reach inside nk_being().
Luckily this character isn't actually used in either Russian or Belarussian, removing it fixes everything.
```
nk_rune ranges_font[] = {
    0x0020, 0x007E,		/* Ascii */
    0x00A1, 0x00FF,		/* Symbols + Umlaute */
    0x0410, 0x044F,		/* Russian */
    0x0450, 0x0450,		/* Cursed cyrillic */
    0x3000, 0x303F,		/* CJK Symbols and Punctuation */
    0x3040, 0x309F,		/* Hiragana */
    0x30A0, 0x30FF,		/* Katakana */
    /* 0x4E00, 0x9FFF, */	/* Kanji 4E00–9FFF */
    0
}; 
```
After inclusion of 0450, this
![Screenshot from 2021-05-15 14-36-00](https://user-images.githubusercontent.com/60887273/118357379-279a6700-b57a-11eb-97e0-22007f2b5db0.png) becomes this ![Screenshot from 2021-05-15 14-36-24](https://user-images.githubusercontent.com/60887273/118357384-2a955780-b57a-11eb-8d00-ea14dfb84ba7.png)

**Comment by dumblob** [comment]
Thanks for tracking this down! Do you think it's a sensible fix to not include the `ѐ` character or we shall somehow fix the bad computation, shifts etc.? If the latter, shouldn't we invite also authors of the backend font library Nuklear is using by default ([`stb_truetype.h`](https://github.com/nothings/stb )) into this discussion?

**Comment by FrostKiwi** [comment]
> Thanks for tracking this down! Do you think it's a sensible fix to not include the `ѐ` character or we shall somehow fix the bad computation, shifts etc.? If the latter, shouldn't we invite also authors of the backend font library Nuklear is using by default ([`stb_truetype.h`](https://github.com/nothings/stb)) into this discussion?

If the issue comes form stb_truetype, then inviting the authors makes sense. But I have not dived into the code yet to understand where it actually happens...

**Comment by FrostKiwi** [comment]
The fault lies within how nk_font_config is handled and how those nk_font_config glyph ranges are transferred to the nk_font_atlas. This lowers the suspicion of stb_truetype being at fault, though it's not off the hook.

Adding ѐ to a nk_font_config corrupts every following glyph only in the same nk_font_config. Eg.: If Japanese characters are handled by another nk_font_config, the Japanese characters remain untouched. But the following cyrillic characters after ѐ are all off by one, even though they are all part of the same atlas.
I was kinda hoping valgrind would just give me the answer as to where this happens, but that was a bit too optimistic^^

I'll properly dig with a debugger later on.

<details>
<summary>
This reminds of...
</summary>

![Screen_Shot_2018-04-25_at_12 24 22_PM](https://user-images.githubusercontent.com/60887273/118400417-df567400-b661-11eb-82f7-8604cbbc6f4d.png)
</details>

**Comment by FrostKiwi** [comment]
Under certain conditions, other characters after 0x0450 can be made to off-by-one corrupt the glyph ranges. For some reason, I can combine 0x0450 and 0x0456 to offset the glyphs by 2 forward. But 0x0451 is fine. Something is strange about that extended cyrillic unicode block, or those hex number ranges

**Comment by FrostKiwi** [comment]
Solved by https://github.com/Immediate-Mode-UI/Nuklear/issues/239

**Comment by dumblob** [comment]
@FrostKiwi it seems you have quite some interest in Nuklear. Could you maybe review some of the existing PRs as all of us current Nuklear maintainers, are too busy to handle that.

After few good reviews you can get full admin access to this repo (as we like to extend the number of maintainers to increase the infamous [bus factor](https://en.wikipedia.org/wiki/Bus_factor ) and to allow the Nuklear ecosystem thrive).

**Comment by FrostKiwi** [comment]
> @FrostKiwi it seems you have quite some interest in Nuklear. Could you maybe review some of the existing PRs as all of us current Nuklear maintainers, are too busy to handle that.
> 
> After few good reviews you can get full admin access to this repo (as we like to extend the number of maintainers to increase the infamous [bus factor](https://en.wikipedia.org/wiki/Bus_factor) and to allow the Nuklear ecosystem thrive).

I always loved the possibility of doing UI with nothing but C, so yeah, I always had interest since I found @vurtun's original repo.
Thanks for the offer. I'll go right ahead and review some PRs this week...
