### ISSUE TITLE
UTF8 glyphs index is wrong

### ISSUE THREAD

**Issue by user23333** [Immediate-Mode-UI/Nuklear#307]
if continue glyph_count not increment...

![image](https://user-images.githubusercontent.com/43466088/122606737-fc8cc100-d0ab-11eb-8cd3-e39b05259a37.png)
![image](https://user-images.githubusercontent.com/43466088/122607040-8472cb00-d0ac-11eb-9b2a-9540a7081d32.png)

**Comment by dumblob** [comment]
Could you share your solution to the problem?

**Comment by user23333** [comment]
> Could you share your solution to the problem?

i just let glyph_count increment

`
                    if (!pc->x0 && !pc->x1 && !pc->y0 && !pc->y1) 
                    {
						glyph_count++;
                        continue;
                    }
`

**Comment by dumblob** [comment]
Thanks!
