### ISSUE TITLE
Variable In Label

### ISSUE THREAD

**Issue by Dubhghall** [Immediate-Mode-UI/Nuklear#311]
How do I put a variable such as an int in a nuklear label to display like

Max Count: 23

**Comment by Hejsil** [comment]
I think `nk_labelf` is what you are looking at. It is basically the `printf` for labels

**Comment by Hejsil** [comment]
There is also `nk_value_int` and friends.

**Comment by Dubhghall** [comment]
@Hejsil 

legend ty
