### ISSUE TITLE
Widget Position

### ISSUE THREAD

**Issue by q5aDev** [Immediate-Mode-UI/Nuklear#312]
Is there anyway to set an exact widget position like with ImGui where they use:

ImGui::SetCursorPos();

**Comment by Hejsil** [comment]
I think you are looking for the `nk_layout_space_xxx` functions

**Comment by Dubhghall** [comment]
i cant seem to get any of them working

**Comment by q5aDev** [comment]
ok thanks u can close this now ty for help
