### ISSUE TITLE
demos dont compile

### ISSUE THREAD

**Issue by phoebe-leong** [Immediate-Mode-UI/Nuklear#318]
ok so first of all i cant code in Nuklear or do anything basically because according to my compiler (g++) the functions havent been defined properly. 
And both ``nuklear.h``'s (inside src folder and outside) don't define the functions that I'm trying to use (window making). 
I also tried to compile the ``calculator.c`` demo project (it wasnt even linked up i had to do it) and it didnt compile.

**Comment by lockie** [comment]
Mind sharing the error messages and the command you're using to compile with us?

**Comment by phoebe-leong** [comment]
I've since deleted the source code from my computer (basically i gave up because this has been a recurring theme whenever i try gui) but i used g++ to compile my program.
i remember trying to create a window (however you do that, ive forgotten) and i had trouble figuring out which libraries to include
the errors given were fatal, basically saying that the functions in question were defined but not given any code to execute.
and i couldnt find where the function to create a window had been properly defined so i assumed that they were in ``windows.h`` so i linked that up to my program but it still didnt work.
ill retry compilation and give you the full errors from g++ asap but for now i think this will have to do (sorry)

**Comment by phoebe-leong** [comment]
Errors when compiled with g++:
```
Undefined symbols for architecture x86_64:
 "_nk__begin", referenced from:
  _main in main-fdaf23.o
"_nk_end", referenced from:
 _main in main-fdaf23.o
```
Code just in case it's needed:
```cpp
#include "nuklear.h"

int main() {
    nk_context* context;
    nk__begin(context);
    nk_end(context);
}
```

**Comment by lockie** [comment]
For this to comile, you'll have to define `NK_IMPLEMENTATION` prerprocessor symbol before Nuklear header inclusion, like that:
```c
#define NK_IMPLEMENTATION
#include "nuklear.h"

int main()
// ...
```

Also, `windows.h` is Windows' system header, it has nothing to do with Nuklear.

Also, to compile a demo, you'll have to pick a backend implementation. Considering you're using Windows, I suggest one of `d3d11`, `d3d9`, `gdi` or `gdip`. Just compile `main.c` out of selected backend's folder.

**Comment by phoebe-leong** [comment]
oh my gosh im so stupid thank you
