### ISSUE TITLE
Create and Port Over Wiki

### ISSUE THREAD

**Issue by kiwidoggie** [Immediate-Mode-UI/Nuklear#32]
The previous wiki, even if sparse had screenshots and examples of how to use most things in nk, would be nice to have that moved over or one created for it to be expanded on. Visualizing was one of the hardest parts of using this toolkit, but after it's been smooth sailing.

**Comment by 2asoft** [comment]
Old wiki now moved to this repo (in the same state as it was, so likely somewhat outdated now).
