### ISSUE TITLE
Nuklear Cross integration

### ISSUE THREAD

**Issue by twaik** [Immediate-Mode-UI/Nuklear#33]
Hi. There is a library called [Nuklear Cross](https://github.com/DeXP/nuklear_cross) which can help us to hide hardware/software differences from developer and just let him/her write platform independent application. Can this be integrated to Nuklear? 
If yes you can get rid of demo folder replacing it with single demo file. Selecting target platform can be implemented as providing single -D to the compiler or including header file.

**Comment by Nielsbishere** [comment]
I don't know if it belongs in Nuklear core, because it makes nuklear more "bloated", which is what it's trying to avoid (it should stay a single header library). However, it does look like a very cool project and demos could use it very well imho.

**Comment by twaik** [comment]
You can try to make it packing to a separated source file. Then a demo source should include nuklear.h or nuclear++.h (which will include nuclear.h).

**Comment by Nielsbishere** [comment]
Perhaps, but one of the things I like about nuklear is that it is platform & api independent. Adding that into main gets rid off that. I would think maybe a nuklear_cross.h or nuklear+.h would be handy for other people though, but I myself wouldn't use it.

**Comment by twaik** [comment]
The main idea is making it something like plugin/addition available to be used without modifications. You can use it or ignore. This will make Nuklear ready to be used right after cloning repo. Nuklear itself will be platform&api independent. Nobody will force developers/users to use nuklear+.h

**Comment by Nielsbishere** [comment]
Yeah that sounds good to me, I'm only a contributor though. A big problem with this though would be that it will open issues that could come from being able to support different platforms and different APIs.
