### ISSUE TITLE
cannot load font

### ISSUE THREAD

**Issue by jacknicklenson** [Immediate-Mode-UI/Nuklear#331]
Hi,
Firstly thank you for this imgui :)

And if we come to my problem is:

https://gist.github.com/jacknicklenson/a4cffc9081db4cdef5d6486ad834dc85

in this gist I share the code that i wrote. My problem is when i compile and run it gives this error in console:
```console
dnuklear.out: ./nuklear.h:20123: nk_begin_titled: Assertion `win->seq != ctx->seq' failed.
Aborted
```
If i debug the code in gdb; in while loop it completes its first cycle successfully however in the second cycle when it hits the ```if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220)....``` which is  line 169
it is crashing with that error that I pasted the error above.
What am i doing wrong here ?
I wrote the code according to the demo/glfw_opengl3 but not copied all code because i want to go minimal at first, not whole bunch of code from that example. I can compile and run that demo example successfully but not mine :(

IMHO, Can't we just simply load font like that;
```c
nk_font *fnt = nk_load_font_from_file("path/to/.ttf");
nk_init_default(&ctx, &fnt->handle);
```
similar to the raylib library => https://github.com/raysan5/raylib/blob/master/examples/text/text_font_loading.c

Thanks in Advance

**Comment by Hejsil** [comment]
There is an excellent comment above the assert you have triggered:
https://github.com/Immediate-Mode-UI/Nuklear/blob/6e80e2a646f35be4afc157a932f2936392ec8f74/src/nuklear_window.c#L191-L198

Basically, you're missing a `nk_clear` and the end of your loop.

**Comment by CODESOLE** [comment]
Thx it worked xD.
