### ISSUE TITLE
Multiple Instance Support

### ISSUE THREAD

**Issue by mgood7123** [Immediate-Mode-UI/Nuklear#341]
Does Nuklear support Multiple Instances?

For example

NuklearView contains its own instance of Nuklear and a Texture to draw to

In which each instance of NuklearView is completely isolated from all other instances of NuklearView

There can be many instances of NuklearView all drawing different things to, mixed with other views which draw 3D and 2D stuff

Basically rendering and compositing each view

Eg assuming draw order of
```
CubeView
NuklearView
CubeView
PainterView
NuklearView
```
Is this possible without needing a global NuklearView and trying to subcomposite that?

Eg
```
Hide Nuklear Window B and draw Nuklear window A to View A
Hide Nuklear Window A and draw Nuklear window B to View B
```

Assuming the window can be correctly and all popups and such are somehow contained to the intended region within the global Nuklear view

And a bunch of other things such as window management and so on that ultimately result in a very complex `Compositing Nuklear Windowing System integrated into an existing Compositing Windowing System` which I would rather avoid if possible

**Comment by RobLoach** [comment]
Make multiple instances of `struct nk_context ctx;`, and you'll be able to handle the different contexts independently.
