### ISSUE TITLE
Hi! Does this library work in DRM / non-X11 mode?

### ISSUE THREAD

**Issue by Fredrum** [Immediate-Mode-UI/Nuklear#342]
Hello!!
I came here as I'm shopping around for a nice small GUI toolkit for Linux and someone mentioned Nuklear!
One of my main needs is being able to render straight to screen in a non X11 (and non-wayland) environment. Basically from the raw CLI.
Can I do that with Nuklear?

Cheers!

**Comment by Hejsil** [comment]
All Nuklear does is create a list of draw commands from the UI elements you want to draw. It is then your job to figure out how to draw this list of command to the backend of your choice. Nuklear provides demos of how to do this for common backends like X11, opengl, SDL, directX and others. As long as you have some way of drawing pixels to something, you can use Nuklear with it. Hope that answers your question :)

**Comment by Fredrum** [comment]
Ah ok I see!  So I need to make my drawing system render without x11 and I should be good.
Thanks I'll check out your examples! Thanks for the quick feedback!

**Comment by Fredrum** [comment]
Actually checking out the sdl_gles2 example  (I'm aiming to use on a Raspberry Pi4) I have a question.
In terms of how much prep/setup work I might have to do is the main.c a representation of that?
Or will I also need to create my own project version of 'nuklear_sdl_gles2.h'  ?

**Comment by Hejsil** [comment]
The `nuklear_X.h` tend to contain all the code required to initialize and draw to the backend for that demo. There is no requirement to structure it exactly like the demos do. The main mostly just contains using Nuklear itself.
