### ISSUE TITLE
Instructions on how to install and configure this library

### ISSUE THREAD

**Issue by Unicorn7141** [Immediate-Mode-UI/Nuklear#345]
Hi, I am new to C++ and I wanna use this library, but I have no idea how to install it and add it to my project...
I mainly use CLion, VS 2019 and Code::Blocks (it depends on the machine I use).

I tried using `conan` but it doesn't seem to work, same goes to `vcpkg`

If you could please add the instructions to the README it'd be great

**Comment by Hejsil** [comment]
Hi. Nuklear is what is called a header only library. I would suggest learning about this concept and then come back and read the [Building](https://github.com/Immediate-Mode-UI/Nuklear#building) section of the readme for specific instructions for building Nuklear.

**Comment by RobLoach** [comment]
There isn't a `conan` package defined for this, nor a `vcpkg`. As Hejsil mentioned, it's header only. You just need to include it in order to use it. Copy/paste nuklear.h into your project, and use.
