### ISSUE TITLE
Kotlin/Native : Getting error undefined reference when using generated C wrappers ?

### ISSUE THREAD

**Issue by RageshAntony** [Immediate-Mode-UI/Nuklear#361]
I able to run the demo program in C++ IDE So decided to run via kotlin Native

So I imported the files in this folder to cinterop folder and successfully generated Kotlin wrappers

https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/glfw_opengl2

When trying to run the program that contains calls to Nuklear library , I am getting error

`/tmp/konan_temp10440296917428106488/result.o:out:function com_myapp_applib_nk_glfw3_init_wrapper1029: error: undefined reference to 'nk_glfw3_init'`

I able to run GLFW window creation without calling Nuklear library , but when using nuklear wrapper I am getting this errors

How to solve this ?

My code:
https://gist.github.com/RageshAntony/d25232763682d2a15acbabaa1cca08bc

**Comment by RobLoach** [comment]
I don't have any experience with Kotlin, but you do need to define `NK_IMPLEMENTATION` before including nuklear.h.

**Comment by RobLoach** [comment]
`NK_IMPLEMENTATION` should be in ONE of your `.c` files, rather than a .h file :wink:
