### ISSUE TITLE
Version strategy: Do not prefix with 0

### ISSUE THREAD

**Issue by RobLoach** [Immediate-Mode-UI/Nuklear#382]
Right now, we use a [semver](https://semver.org/)-esque strategy, but we are prefixing `#.##.#`, for example `4.09.1`. This is fine for having the versions align in nuklear.h, but it doesn't really make sense for semantic version numbering. It should likely be `#.#.#`.

I'm proposing removing the prefixing `0` from the minor number in the middle to more align with actual semantic versioning.

**Comment by dumblob** [comment]
I agree. But I'm undecided on whether we shall rewrite the whole history log to this new format or just use this new format in new commits.

Maybe the history rewrite is not such a big deal and should be done to ease parsing etc. on user sides. IDK

**Comment by RobLoach** [comment]
Happy with keeping the old format for past versions. Updated the PR https://github.com/Immediate-Mode-UI/Nuklear/pull/384
