### ISSUE TITLE
Problematic icon loading path

### ISSUE THREAD

**Issue by stefanos82** [Immediate-Mode-UI/Nuklear#389]
https://github.com/Immediate-Mode-UI/Nuklear/blob/aa47577bae8098301a3ee604a6e6d1670ea0b73d/example/extended.c#L803-L824

`icon` is located inside `example` and it therefore cannot find the right path to load the image.

![image](https://user-images.githubusercontent.com/1777466/147153821-4afeef2d-9f5c-4762-b6ce-f4f46e6fc8c8.png)

Either sub-folder(s) should be move outside the `example` directory or replace `../icon/` to `./icon/`.

**Comment by RobLoach** [comment]
You'll want to `cd bin` before running `./extended`. I've created a small Pull Request to avoid needing the `bin` directory for the demos, hope to apply the same pattern to the `example` directory after this. Thanks!
