### ISSUE TITLE
(Question) Example of using nuklear with SDL2's render directly as opposed to copying over a surface?

### ISSUE THREAD

**Issue by Nosh-Ware** [Immediate-Mode-UI/Nuklear#392]
I'm pretty sure I'm a bit confused here, as I'm still learning about things like rendering and the like; but I was wondering why I always see either implementations of nuklear in the demos folder only using some form of software rendering or OpenGL/glfw, and nothing in regards to SLD's render being used directly. Is this simply something that no one has had an interest in doing yet, or is there something in the way nuklear works that make this difficult or impossible to do? I'm asking because I am looking to use this for one of my projects, as from what I understand so far this seems to be exactly what I want in a GUI lib; but I need help solving a few kinks. If this isn't the best place to post this I can move this elsewhere.

**Comment by dumblob** [comment]
> I'm pretty sure I'm a bit confused here, as I'm still learning about things like rendering and thew like; but I was wondering why I always see ither implemenataions of nuklear in the demos folder only using some form of software rendering or opengl/glfw, and nothing in regards to SLD's render being used directly. Is this simply something that no one has hgad intrest in doing yet, or is thewre someing in the way nuklear works that make this difficult or impossible to do.

Actually the `example/` directory is meant to be compilable on most platforms and show rather "traditional" use of **Nuklear** (it doesn't want to show how to use OpenGL nor SDL nor any other technicalities but really focus on Nuklear). The `demo/` directory on the other hand is a set of backends volunteers decided to provide us (therefore it's officially not part of Nuklear and thus not supported - but in practice there are very few issues with backends we had so far so don't be afraid of this :wink:).

>I'm asking because I am looking to use this for one of my progects, as from what I understand so far this seems to be exactly what I want in a GUI lib; but I need help solving a few kinks. If this isn't the best place to post this I can move this elsewhere.

Sure, ask here about anything. We're a small group, but someone will eventually answer :wink: (but the more specific & special question you'll ask, the more time you'll probably wait for the answer, so don't give up even after months).

**Comment by Nosh-Ware** [comment]
Thanks for the reply. I looked into it more and I'm starting to see what's going on in the sdl demo. Still having trouble seeing how everything works with nuklear itself hence why I was more eager to see if a simpler API for using it exactly how I wanted was available. I'll keep on it and I'll be sure to ask if I got any questions.
