### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by RobLoach** [Immediate-Mode-UI/Nuklear#397]
Rafał Jopek has suggested the following for a logo for Nuklear!

![Screenshot_20220109-194027](https://user-images.githubusercontent.com/25086/148707814-87e786b0-3c08-4e9b-9b31-b1d11b75a61a.png)

[nuklear.svg](https://user-images.githubusercontent.com/25086/148707795-9fe3364a-294c-4960-88bb-e474d56c7de6.jpg)

**Comment by dumblob** [comment]
Nice! Why not? In the worst case we can change the logo any time if there is demand/proposal :wink:.

**Comment by RobLoach** [comment]
Didn't let me upload the .svg, so here it is in a zip [nuklear.zip](https://github.com/Immediate-Mode-UI/Nuklear/files/7843321/nuklear.zip)

**Comment by RobLoach** [comment]
https://github.com/Immediate-Mode-UI/Nuklear/issues/401
