### ISSUE TITLE
Checkbox label box too big?

### ISSUE THREAD

**Issue by NamelessG0d** [Immediate-Mode-UI/Nuklear#398]
Hi,
Started using nuklear to make a GUI Overlay, and tried using nk_checkbox_label in rows.
Now, when I press any checkbox, the other ones around will also turn on/off without affecting the variable linked with it...
Maybe I'm using them not in the right way?

Another issue I have is that they will all show as turn on at init even when the bool associated isn't...

I used the old nuklear project, so if it's something you already patched, could you guide me to the push so I can fix it in my version?
Thanks in advance,
Nameless

Snippet :
`			nk_layout_row_dynamic(ctx, 20, 2);
			nk_checkbox_label(ctx, "Enable", (int*)&cfg->visual_enable);
			nk_checkbox_label(ctx, "Names", (int*)&cfg->visual_names);
`

**Comment by dumblob** [comment]
I hope you got this solved.

Btw. we try to be backward-compatible with API & ABI (more or less), so you shouldn't have much problems using the current master instead of trying to cherry-pick only the relevant patches :wink:.

**Comment by NamelessG0d** [comment]
Hey, I heavily modified the old version to be more lightweight / efficient (edited loading / unloading and function I would never use) in a effort to reduce the overall size of the binary, which is why I asked for the push...

I'll keep you updated if I figure out why it was happening 👍

**Comment by krispybyte** [comment]
Hey everyone,
This is quite an old issue, but just in case anyone stumbles upon this issue in the future - The problem happens whenever the "active" parameter (third parameter) passed to the `nk_checkbox_label` function is of type `bool` (1 byte). To fix this, simply use `nk_bool` or `int` (4 bytes) instead.
