### ISSUE TITLE
Cant compile under C++ 20

### ISSUE THREAD

**Issue by M0n7y5** [Immediate-Mode-UI/Nuklear#402]
Hello i have a problem with compilation in my C++ 20 project. When i try to compile it it gives me this error:
![image](https://user-images.githubusercontent.com/17201053/151449456-7ff02910-f29a-45cf-ac98-f70c61883086.png)

It looks like that it need C DirectX API so i tried to do this but no luck
![image](https://user-images.githubusercontent.com/17201053/151449817-b7d1c98e-9cef-4bcb-9d53-d60591e865d3.png)
Any ideas how to fix it?

**Comment by RobLoach** [comment]
Looks like you may need to link Direct3D in your compiler.

**Comment by M0n7y5** [comment]
I tried to link it against d11 libs but no luck. It works only in .c file ... not .cpp
Is there any way to use this in C++ project or should i need to stick with C?

![image](https://user-images.githubusercontent.com/17201053/151633482-4d54e757-b898-4c67-84d4-1ff99e4b772c.png)

**Comment by M0n7y5** [comment]
I also tried build it in 2 different machines

**Comment by RobLoach** [comment]
Nuklear works in C++, you're just running into D3D issues. You'd have to link D3d, and ensure the include directory is set.... Nuklear has no real dependencies itself.

**Comment by M0n7y5** [comment]
But i have everything linkedand setuped 
![image](https://user-images.githubusercontent.com/17201053/151634421-d83c2b84-3fae-4c2c-ba06-f1a9e7898931.png)

**Comment by RobLoach** [comment]
Does d3d11.h include? Looks like it's not finding even the function declarations.

**Comment by M0n7y5** [comment]
yes ... its already part of this file
![image](https://user-images.githubusercontent.com/17201053/151635114-807aa0d0-c00f-47c4-b07f-a38f3f46e122.png)

**Comment by M0n7y5** [comment]
when i move my code to somefile.c then it works

**Comment by RobLoach** [comment]
Correct. That implementation define should be in a .c or .cpp file.

**Comment by M0n7y5** [comment]
I was trying to use that DX11 renderer from demo folder. Nevertheless I got it working.

**Comment by RobLoach** [comment]
What did you end up doing?

**Comment by ExoticNx** [comment]
What did you do to get this working having the same issue. @M0n7y5
