### ISSUE TITLE
Assertion failed: elem, file nuklear.h, line 15380

### ISSUE THREAD

**Issue by paramsiddharth** [Immediate-Mode-UI/Nuklear#418]
# Assertion failed: elem, file nuklear.h, line 15380
Error comes on Windows 10, GCC 10.3.0 (MSYS2).

Header used: [nuklear.h.zip](https://github.com/Immediate-Mode-UI/Nuklear/files/8214687/nuklear.h.zip)

<details>
<summary>Code (click to view)</summary>

```c
#define NK_INCLUDE_FIXED_TYPES
#define NK_IMPLEMENTATION
#include "nuklear.h"

#include <stdlib.h>

const int MAX_MEMORY = 128;

typedef enum {
	EASY,
	HARD
} ease;

int main() {
	ease op = EASY;
	double value = 0.6f;
	struct nk_context ctx;

	const char* fontname = "monospace";
	const struct nk_user_font font = {
		.userdata = fontname,
		.height = 20,
		.width = 20
	};

	nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);

	if (nk_begin(&ctx, "Hi",
		nk_rect(50, 50, 220, 220),
		NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_CLOSABLE)) {
		nk_layout_row_static(&ctx, 30, 80, 1);
		if (nk_button_label(&ctx, "Click")) {
			// TODO
		}
	}

	nk_end(&ctx);

	return EXIT_SUCCESS;
}
```

</details>

**Comment by FrostKiwi** [comment]
In this code, there is no backend connected. Check out the demo folder to see how to startup a back end, so GUI code may run.

**Comment by RobLoach** [comment]
I'd recommend trying out one of the SDL backends. SDL is relatively easy to get up and running, and is cross platform, so it'll run on Windows for you no problem.
