### ISSUE TITLE
Problems compiling on aarch64 (with solution)

### ISSUE THREAD

**Issue by michaelcartner** [Immediate-Mode-UI/Nuklear#420]
Building on an M1 mac these asserttions failed:
```
NK_STATIC_ASSERT(sizeof(nk_size) >= sizeof(void*));
NK_STATIC_ASSERT(sizeof(nk_ptr) >= sizeof(void*));
```

I solved it by modifying the following:
`#if defined(__x86_64__) || defined(__ppc64__)`
to
`#if defined(__x86_64__) || defined(__ppc64__)  || defined(__aarch64__)`
and now it's building without errors

**Comment by dumblob** [comment]
Thanks! PRs are very much welcome :wink:
