### ISSUE TITLE
Resetting `style.window.fixed_background` to default?

### ISSUE THREAD

**Issue by tree786isback** [Immediate-Mode-UI/Nuklear#428]
Sorry if this is an extremely trivial question, I couldn't seem to find any info so I'll ask here. I was wondering what is the best way to reset ` ctx->style.window.fixed_background` to the nuklear default value after modifying it? I.e., I have created a transparent window which acts as a canvas (for rendering 2D primitive shapes with no bg), and I've set  ` ctx->style.window.fixed_background = nk_style_item_color( nk_rgba(0, 0, 0, 0) )` to make sure the BG is 100% transparent. However, after the canvas loop, I'd like to start adding the default nuklear windows. But when I do that, all my non-canvas windows become transparent, which is undesirable. Here is my setup:
```
    //set default theme
    set_style(ctx, THEME_RED);

    //TRANSPARENT CANVAS LOOP
    nk_glfw3_new_frame(&glfw);
    ctx->style.window.fixed_background = nk_style_item_color( nk_rgba(0, 0, 0, 0) );
    //add window
    nk_begin(ctx, "canvas window", nk_rect(0, 0, getWidth(), getHeight()), NK_WINDOW_BACKGROUND|NK_WINDOW_NO_SCROLLBAR);
      //add progress bar
      nk_layout_row_static(ctx, getWidth(), getHeight(), 1);
      canvas = nk_window_get_canvas(ctx);

      //draw a filled rect
      float roundedness = 5.f;
      nk_fill_rect(canvas, nk_rect(10, 10, 120, 90), roundedness, nk_rgba(0, 0, 255, 230));
    //end frame
    nk_end(ctx);

    //NORMAL WINDOW (OPAQUE) LOOP
    // ctx->style.window.fixed_background = nk_style_item_color( nk_rgba(0, 0, 0, 0) );
    nk_begin(ctx, "normal window!", nk_rect(50, 50, 300, 300), NK_WINDOW_BORDER|NK_WINDOW_SCALABLE|NK_WINDOW_TITLE|NK_WINDOW_MOVABLE);
      //add progress bar
      nk_layout_row_static(ctx, 50, 200, 1);
      nk_button_label(ctx, "button");
    //end frame
    nk_end(ctx);

```

I could reset  `ctx->style.window.fixed_background` to a hardcoded value after I finish canvas, but is there a more elegant way of doing this? I.e something like 
```
ctx->style.window.fixed_background = nk_style_item_color( NK_DEFAULT_STYLE );
```

**Comment by dumblob** [comment]
In immediate mode UIs you're usually better off saving the state to your own variables and then restoring it from there:

```c
struct nk_color tmp = ctx->style.window.fixed_background;
ctx->style.window.fixed_background = nk_style_item_color( nk_rgba(0, 0, 0, 0) );
...
ctx->style.window.fixed_background = tmp;
```
(note I didn't test this code, so there might be some typos etc.)

**Comment by tree786isback** [comment]
That's a smart idea, didn't think of that. Thnks!
