### ISSUE TITLE
Optimal way of setting font sizes when using canvas rendering?

### ISSUE THREAD

**Issue by tree786isback** [Immediate-Mode-UI/Nuklear#429]
I am trying to find a way to set the size of a `nk_draw_text` per instance. Take this code which uses canvas rendering:
```
      //add small text
      std::string small_text = "small text";
      nk_draw_text(canvas, nk_rect(10, 300, small_text.size()*100, small_text.size()*100), small_text.c_str(), small_text.size(), &font->handle, nk_rgba(0, 0, 0, 255), nk_rgba(0, 255, 0, 255));

      //add large text
      std::string large_text = "large text";
      nk_draw_text(canvas, nk_rect(10, 300, large_text.size()*100, large_text.size()*100), large_text.c_str(), large_text.size(), &font->handle, nk_rgba(0, 0, 0, 255), nk_rgba(0, 255, 0, 255));

```
I.e. I am adding to `nk_draw_text` "instances", and I'd like to set the size of each one. The only way I currently understand is by defining a custom `struct nk_font* font` with my given size for each `nk_draw_text`, which seems quite inefficient since I am already creating fonts like this:
```
  font = nk_font_atlas_add_from_file(atlas, "./Custom-Font.ttf", 22.f, NULL);
```
And if I want to create many different `nk_draw_text` with different sizes, it seems unoptimal to create to create an `nk_font*` for each one (same font, different size). Is there a better way to specify the size of each added `nk_draw_text` instance?

**Comment by dumblob** [comment]
I'm a bit unsure I understand all your concerns here :wink:.

Generally you can bake font and downscale it (upscaling would make it blurry) without much rebaking but otherwise I don't think there is much you can optimimez in the whole process - in the end you need to get the pixels out of the font and different font size means different pixels which means new computation :wink:.

But maybe others (at least @RobLoach @Hejsil @kbolino ) would want to comment more on this.

**Comment by tree786isback** [comment]
Alright. So is it fine to create a new `struct nk_font*` object for each text size? Because that's the only way I know how to create different text sizes with the same `ttf` font file

**Comment by kbolino** [comment]
First, I'd recommend reading https://github.com/Immediate-Mode-UI/Nuklear/wiki/Complete-font-guide#font-sharpness which @dumblob shared with me in another context. Note that, especially on standard/low-DPI displays, getting the fonts to look nice requires tweaking their sizes and configs. So if you want to support multiple font sizes on low-DPI displays, you'll want to create multiple fonts, each one hand-tuned to perfect its appearance. The reason why this is necessary is that the font engine in Nuklear is pretty effective at its job (rasterizes font outlines, anti-aliases output, applies kerning, etc.) but doesn't do anything *too* fancy (fancy things it doesn't do: subpixel antialiasing, hinting, [this magic](https://github.com/Chlumsky/msdfgen)). 

Second, based on my recent experience, if your primary concern is high-DPI displays (modern smart phones, 4K+ monitors, etc.), then you can "cheat" with a single baked font. Bake it at the largest size you need and then scale its `height` down proportionally to the output size you want. I found this useful in the context of making fonts look good on high-DPI displays in the first place (details [in this PR](https://github.com/Immediate-Mode-UI/Nuklear/pull/427) if you're interested). Short version:

1. Bake the largest font you need at 2 times the apparent size you want
2. Set `font->handle.height /= 2` &larr; this is your baseline font
3. Suppose you started at apparent size 24 and now you want size 16:
    ```c
    struct nk_font *font;
    /* ... */
    nk_style_set_font(ctx, &font->handle);
    /* ... */
    nk_label(&ctx, "some_text at size 24", NK_TEXT_LEFT);
    float original_height = font->handle.height;
    font->handle.height *= 16.0 / 24.0;
    nk_label(&ctx, "some text at size 16", NK_TEXT_LEFT);
    font->handle.height = original_height;
    ```

YMMV about the quality of the results. I set texture filtering to best quality possible and the output looked decent.

**Comment by tree786isback** [comment]
Thanks very much for all this info ! That explains everything I need to know very well !
