### ISSUE TITLE
Segfault when trying to copy `nk_edit_string` contents

### ISSUE THREAD

**Issue by tree786isback** [Immediate-Mode-UI/Nuklear#431]
Hi

I have the following code which uses the `nk_edit_string` with its default `nk_filter_default` filter:

```
    const int MAX_CHAR = 128; //maximum number of characters
    static char char_buffer[1][MAX_CHAR]; //characters will be stored here
    static int number_of_chars {}; //total number of characters typed in

    nk_begin(ctx, "text edit", nk_rect(0, 0, getWidth()*0.25f, getHeight()*0.5f), NK_WINDOW_SCALABLE|NK_WINDOW_TITLE|NK_WINDOW_MOVABLE);
      nk_layout_row_dynamic(ctx, nk_widget_height(ctx)*0.25f, 1);
      nk_edit_string(ctx, NK_EDIT_FIELD, char_buffer[0], &number_of_chars, MAX_CHAR, nk_filter_default);
    nk_end(ctx); // end frame
```
When I type something, then try to copy it by (first highlighting it) pressing the `Ctrl + C` key combo, I get a segfault with this error:
```
Bus error (core dumped)
```
![Peek 2022-03-18 00-29](https://user-images.githubusercontent.com/97201835/158915036-f2122f21-b28a-4989-a71b-5edf0e76a76c.gif)

I've run `gdb` to find where it's happening, and it points me to `glfwPlatformSetClipboardString`. Not sure which LoC in the nuklear source references that function. I'm running this on a manjaro system FYI.
Any ideas what could be the issue?

**Comment by tree786isback** [comment]
Well I think this is because I was statically casting to a (nk_glfw*), to force it to compile. See #433  for more info. I'll close this now

**Comment by tree786isback** [comment]
I'll re-open this as #434
Here are test files
[broken textedit.zip](https://github.com/Immediate-Mode-UI/Nuklear/files/8311311/broken.textedit.zip)
If you try and copy or paste using `Ctrl + C` or `Ctrl + V` , it crashes

**Comment by RobertLemmens** [comment]
This is probably to do with the glfw3 reference backend. I took a look at the included code and `nuklear_glfw_gl3.h` seems to create an incorrect userdata pointer in the `nk_glfw3_init` function. If you go to line 384 of that file and change it to not take a reference to a pointer, but the pointer itself, it should work.

```C
NK_API struct nk_context*
nk_glfw3_init(struct nk_glfw* glfw, GLFWwindow *win, enum nk_glfw_init_state init_state)
{
    glfwSetWindowUserPointer(win, glfw);
    glfw->win = win;
    if (init_state == NK_GLFW3_INSTALL_CALLBACKS) {
        glfwSetScrollCallback(win, nk_gflw3_scroll_callback);
        glfwSetCharCallback(win, nk_glfw3_char_callback);
        glfwSetMouseButtonCallback(win, nk_glfw3_mouse_button_callback);
    }
    nk_init_default(&glfw->ctx, 0);
    glfw->ctx.clip.copy = nk_glfw3_clipboard_copy;
    glfw->ctx.clip.paste = nk_glfw3_clipboard_paste;
    glfw->ctx.clip.userdata = nk_handle_ptr(&glfw); // <=== here, change to glfw->ctx.clip.userdata = nk_handle_ptr(glfw);
    glfw->last_button_click = 0;
    nk_glfw3_device_create(glfw);

    glfw->is_double_click_down = nk_false;
    glfw->double_click_pos = nk_vec2(0, 0);

    return &glfw->ctx;
}

```

im not to familiar with that code since i made my own opengl backend for nuklear but that seems to be the culprit after a quick test.

**Comment by RobertLemmens** [comment]
verified the window eventually passed to glfwSetClipboardString pointed to something different then the one your getWindow() function has, so it certainly seems to be the case the userdata pointer is wrong 😄
