### ISSUE TITLE
Is it feasible to implement a MIDI sequencer in Nuklear?

### ISSUE THREAD

**Issue by mavavilj** [Immediate-Mode-UI/Nuklear#438]
For example of this kind:

https://static.kvraudio.com/i/b/poly-step-seq-2.jpg

I was struggling to find suitable pre-made components.

**Comment by dumblob** [comment]
There are currently no pre-made MIDI components as far as I know. But look at how other canvas-like components are implemented (e.g. charts) and you should be ready to make your own.

**Comment by mavavilj** [comment]
Okay, but I did not find a good reference for explaining charts.

**Comment by dumblob** [comment]
As we discussed in https://github.com/Immediate-Mode-UI/Nuklear/issues/424 , Nuklear is built around the idea that one'll read the relevant parts of the source code.

In this case it's the implementation of chart functions and other canvas-related functions. It's quite well commented and written in a very readable way. That everything together is the best reference you can even imagine.

**Comment by mavavilj** [comment]
I've progressed a bit with charts, but now I'm confused about how am I supposed to customize the chart to this need I had. I have been reading the code, such as the part around:

https://github.com/vurtun/nuklear/blob/6b9f937475db9280d966f44f469bc80191b5092a/src/nuklear_chart.c#L140

which shows something related to capturing mouse clicks, which I would need in order to modify the slots or something via mouse clicks.

However, I've been confused as to whether I need to modify:

https://github.com/Immediate-Mode-UI/Nuklear/blob/6e80e2a646f35be4afc157a932f2936392ec8f74/src/nuklear_chart.c

or whether, as I thought first (with my limited experience), capture mouse clicks in the main.c (like https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/x11/main.c#L170) and redraw the chart.

**Comment by mavavilj** [comment]
But I am also confused w.r.t. to how much of Nuklear do I need to know in order to modify the .c files. Currently I'm just calling make in /demo/x11/ and having a weak understanding as to how the library actually compiles.

**Comment by dumblob** [comment]
> However, I've been confused as to whether I need to modify:
> 
> https://github.com/Immediate-Mode-UI/Nuklear/blob/6e80e2a646f35be4afc157a932f2936392ec8f74/src/nuklear_chart.c

No, no modification to Nuklear sources is necessary nor recommended.

> or whether I should, as I thought first (with my limited experience), capture mouse clicks in the main.c (like https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/x11/main.c#L170) and redraw the chart.

Yes, this is the correct way. Capture them yourself and conditionally (based on the keys you've captured) call appropriate Nuklear functions - e.g. a button :wink: (which will add all the needed commands for you to the Nuklear command queue which your backend of choice will then render).

> Based on this https://github.com/vurtun/nuklear/blob/6b9f937475db9280d966f44f469bc80191b5092a/src/nuklear_button.c#L63 the library seems to expect that input handling is done in the respective object's .c file?

Please don't read old sources. Read only the content of this repository. Nuklear was kind of rewritten several times in the past by @vurtun and thus we really consider only the latest code from this repository from the `master` branch.

> Then I also became confused about what the /src/ is for since the same stuff is in nuklear.h:
> 
> #441

`/src/` is a source for "amalgamation" (i.e. simple joining of all the files into the final `nuklear.h` by build scripts) - please refer to #441 for answers and further discussion if needed.

**Comment by mavavilj** [comment]
Now I've been wondering, whether I need to understand the "primitive shapes" that Nuklear outputs, because I've had a bit hard time understanding what happens when I call nk_chart_begin ... nk_chart_end. The chart is drawn, but I don't know where and how. See because in Nuklear.h the chart is given only as:

`struct nk_chart {
    int slot;
    float x, y, w, h;
    struct nk_chart_slot slots[NK_CHART_MAX_SLOT];
};`

But now I'm confused as to how to alter the chart structure for example. And to do that I felt like I need to know how something draws a nk_chart using this struct, right?

Any input?
