### ISSUE TITLE
What are the .c files (under /src/) used for if the whole library is in nuklear.h?

### ISSUE THREAD

**Issue by mavavilj** [Immediate-Mode-UI/Nuklear#441]
What are the .c files used for if the whole library is in nuklear.h?

**Comment by RobertLemmens** [comment]
It is the source of the "compiled" header. You edit the source files to make changes to Nuklear, and generate the single header file for usage.

**Comment by mavavilj** [comment]
> It is the source of the "compiled" header. You edit the source files to make changes to Nuklear, and generate the single header file for usage.

Pardon if this is a newbie question, but why cannot one edit the .h directly?

**Comment by RobertLemmens** [comment]
You could but its not recommended. The idea is that distribution and usage becomes easier. For development you usually want some form of structure. I recommend reading the STB FAQ in their readme to find out more about why single header libraries exist, its a really good write up! https://github.com/nothings/stb

**Comment by RobLoach** [comment]
> Pardon, if this is a newbie question, but why cannot one edit nuklear.h directly?

You could edit nuklear.h directly, however, nuklear.h is a combination of all the .c files in the src directory. If you change nuklear.h, your changes may be lost in the next update when it gets updated with [paq.sh](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/paq.sh).
