### ISSUE TITLE
New folder structure - avoid duplicates

### ISSUE THREAD

**Issue by crazyBaboon** [Immediate-Mode-UI/Nuklear#452]
Hi,

I am thinking of submitting a new PR where the following file structure is used. It immediately releases ~0.5mb due to eliminating duplicate files currently existing (**icon** folder and **stb_image.h**) + makes maintenance easier:

Current file structure:
.
├── clib.json
├── demo
│   ├── allegro5
│   ├── common
│   ├── d3d11
│   ├── d3d12
│   ├── d3d9
│   ├── gdi
│   ├── gdip
│   ├── glfw_opengl2
│   ├── glfw_opengl3
│   ├── glfw_opengl4
│   ├── sdl2surface_rawfb
│   ├── sdl_opengl2
│   ├── sdl_opengl3
│   ├── sdl_opengles2
│   ├── sdl_renderer
│   ├── sfml_opengl2
│   ├── sfml_opengl3
│   ├── wayland_rawfb
│   ├── x11
│   ├── x11_opengl2
│   ├── x11_opengl3
│   ├── x11_rawfb
│   └── x11_xft
├── example
│   ├── canvas.c
│   ├── extended.c
│   ├── file_browser.c
│   ├── icon
│   ├── images
│   ├── Makefile
│   ├── skinning.c
│   ├── skins
│   └── stb_image.h

Proposed file structure:
.
├── clib.json
├── common
│   ├── calculator.c
│   ├── canvas.c
│   ├── file_browser.c
│   ├── icon
│   ├── images
│   ├── node_editor.c
│   ├── overview.c
│   ├── skins
│   ├── stb_image.h
│   └── style.c
├── demo
│   ├── allegro5
│   ├── d3d11
│   ├── d3d12
│   ├── d3d9
│   ├── gdi
│   ├── gdip
│   ├── glfw_opengl2
│   ├── glfw_opengl3
│   ├── glfw_opengl4
│   ├── sdl2surface_rawfb
│   ├── sdl_opengl2
│   ├── sdl_opengl3
│   ├── sdl_opengles2
│   ├── sdl_renderer
│   ├── sfml_opengl2
│   ├── sfml_opengl3
│   ├── wayland_rawfb
│   ├── x11
│   ├── x11_opengl2
│   ├── x11_opengl3
│   ├── x11_rawfb
│   └── x11_xft
├── example
│   ├── canvas.c
│   ├── extended.c
│   ├── file_browser.c
│   ├── Makefile
│   └── skinning.c

Before I carry out this work, do you folks (@RobLoach) (@dumblob )(@FrostKiwi ) agree with this new file structure? 

I basically moved every common file to **common** (source code, images, skins and icon), which is now located in the root of the repository.

**Comment by RobLoach** [comment]
Couple things I've thought about...

- The "demo" folder has commonly been referred to as "backends" 🤔
- The common and example files are not really that usable without the use of the demo code, so I could see them being moved down a level within that demo folder...

All in all though, I'm pretty indifferent.

**Comment by crazyBaboon** [comment]
I have created a new branch 'new_folder_structure': https://github.com/crazyBaboon/Nuklear/tree/new_folder_structure

It contains a preview of the new file structure that should eliminate any duplicates. It doesn't compile yet, because I need to change the include paths. 

Let me know if you're happy (@RobLoach , @dumblob , @FrostKiwi) with this new folder structure or if you have any further suggestions.

**Comment by crazyBaboon** [comment]
PR submitted ;)
