### ISSUE TITLE
fix for ttc font 

### ISSUE THREAD

**Issue by loqix** [Immediate-Mode-UI/Nuklear#456]
function nk_font_bake_pack

            const int font_offset = stbtt_GetFontOffsetForIndex((unsigned char*)it->ttf_blob, 0);
            if (font_offset < 0)
                return nk_false;

            if (!stbtt_InitFont(font_info, (const unsigned char*)it->ttf_blob, font_offset))

**Comment by RobLoach** [comment]
Would you mind submitting a Pull Request?
