### ISSUE TITLE
Strange behaviours with different compilers

### ISSUE THREAD

**Issue by HelloWorldlsla** [Immediate-Mode-UI/Nuklear#461]
I did the following:

```
git clone https://github.com/Immediate-Mode-UI/Nuklear
cd Nuklear/demo/glfw_opengl2/
export CC=tcc
make
./bin/demo
```
And when I click on the color picker, I see this:
![image](https://user-images.githubusercontent.com/33597127/169918041-0784bf79-1c8a-4400-bcc5-05f74e929537.png)

instead of this:
![image](https://user-images.githubusercontent.com/33597127/169918107-8d64ac60-cea1-4330-ad29-65a93c929f24.png)

In fact, all kinds of combos have their popup spawning much lower of where it should be.
And if I move the "Demo" window lower, the popup is even lower :/

![image](https://user-images.githubusercontent.com/33597127/169918170-af89fc64-8e25-449a-8ed1-c7146b88f962.png)

**Comment by HelloWorldlsla** [comment]
This issue keeps happening across different opengl version. It also happens with the x11 demos. So I don't think there's any link with the backend used.
And the issue doesn't happen with GCC or CLANG.
My current tcc version is 0.9.27 (x86_64 Linux)

**Comment by aganm** [comment]
Can you try building for the oldest commit to see if this is something new or not? e3aa8df99d1ad4b928e260862fb57a5dfe780400

**Comment by HelloWorldlsla** [comment]
The oldest commit doesn't have any popup to test with. I can run it with any of the compilers tho

**Comment by HelloWorldlsla** [comment]
This commit broke: https://github.com/Immediate-Mode-UI/Nuklear/commit/85d109e3513b5cbf51fbbd287ee6788c121799fc
the commits just before work on both compilers. Commits after it don't work well with TCC.

**Comment by aganm** [comment]
I gave it a try but I can't reproduce the bug.

```
tcc --version
tcc version 0.9.27 (x86_64 Linux)
```

![image](https://user-images.githubusercontent.com/20380758/172070134-11354309-3a62-4de4-98cb-59117f31cd06.png)

**Comment by HelloWorldlsla** [comment]
![screenshot](https://user-images.githubusercontent.com/33597127/173092095-3b7fc364-1518-401f-bd45-87cbb17a0a37.png)

**Comment by HelloWorldlsla** [comment]
I downloaded the very last version of TCC from their git repo, and I no longer have this issue. Also the error "Invalid relocation entry [15]' doesn't show anymore, maybe there's a link between the two?
Anyway, this issue is resolved, I have no idea why.

And thank you for your answers :+1:

**Comment by dumblob** [comment]
We are glad you solved it by the update. Thanks for reporting anyway!
