### ISSUE TITLE
Linker fails with exit code 1 on macos

### ISSUE THREAD

**Issue by JJ-Borbhunter** [Immediate-Mode-UI/Nuklear#479]
I was compiling a personal project using the nuklear library and my compiler threw the following errors:

Undefined symbols for architecture x86_64:
  "_nk_glfw3_font_stash_begin", referenced from:
      _init_gui in gui.c.o
  "_nk_glfw3_font_stash_end", referenced from:
      _init_gui in gui.c.o
  "_nk_glfw3_init", referenced from:
      _init_gui in gui.c.o
  "_nk_glfw3_new_frame", referenced from:
      _main_menu in gui.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It would appear that nuklear_glfw_gl3.h doesn't link to any source files, or I'm missing a library. Same basic thing happens with all the backend headers

I'm using clang through Cmake on macos 10.6 on a M1 chip

**Comment by JJ-Borbhunter** [comment]
Update:  I included the NK_GLFW_GL3_IMPLEMENTATION flag and now i'm instead getting Implicit declaration errors and and incomplete structure errors, but not linker errors

**Comment by JJ-Borbhunter** [comment]
I managed to fix it and get everything to compile. Turns out you can't have the header file included in another header file.

**Comment by dumblob** [comment]
I am glad you fixed it! Yes, includes in single header libs usually have this restriction (as mentioned in Nuklear's readme).

Feel free to close this issue then :wink:.
