### ISSUE TITLE
Incorporate Nuklear for Photoshop filters?

### ISSUE THREAD

**Issue by DougDevCP** [Immediate-Mode-UI/Nuklear#481]
Is it possible to incorporate Nuklear in Photoshop filter GUI development?
I would like to see some 'Hello World' example if someone here have already done it, preferably with GDI renderer.

**Comment by RobLoach** [comment]
Don't believe so. Photoshop filter effects uses its own thing. You could likely recreate the filter system in Nuklear though, but not incorporate it directly into Photoshop
