### ISSUE TITLE
Widget size

### ISSUE THREAD

**Issue by JJ-Borbhunter** [Immediate-Mode-UI/Nuklear#484]
This is a very basic question, but how would one change the size of a widget? I have a main menu with three or four buttons, and I'd like to change the size of the buttons so that they fill the entire window. I'll also want to change the size of other widgets when I create my option menu and in game UI's. I've done similar things with dear imgui but I don't know how to do this with Nuklear.

**Comment by RobLoach** [comment]
Check `struct nk_style_button` and `ctx.style.button`. It has a bunch of options on how to change spacing. Most of those `nk_style` scructs have what you're looking for
