### ISSUE TITLE
xlib: 9slice patch introduced a bug

### ISSUE THREAD

**Issue by riri** [Immediate-Mode-UI/Nuklear#502]
I was working from a checkout 1e4eacca2e3e4abd4d8b793c580c71f2e5315651
After an update to latest on master, all xlib based demos look broken:

![overview demo](https://i.imgur.com/hseHhsC.png)

I found the wrong commit (6322f53cb569bb989873ee8a1b71ae705b230708) and where it occurs (`nk_tree_state_base()` function), but I am not sure about how to fix it.

Indeed, the issue is not visible on other backends (opengl), and the xlib function which draws text also has code to draw the background filling a rectangle, but for which the color is not initialized (hence the rainbow style when running several times).

One solution could be to remove the text background fill (do we have something to say a text has a specific background ?) or to fix the `nk_tree_state_base()` function to correctly initialize the background color.

I would think fixing the function is the solution.

**Comment by RobLoach** [comment]
Thnaks for the report :+1: Certainly is an interesting one. The xlib backend could be touched up a bit.

**Comment by riri** [comment]
Ok I will do a pr
