### ISSUE TITLE
NK_INCLUDE_DEFAULT_FONT not working as expected

### ISSUE THREAD

**Issue by kothman** [Immediate-Mode-UI/Nuklear#508]
I'm sure I'm just setting this up incorrectly, and would love to get some assistance. It's my understanding that defining NK_INCLUDE_FONT_BAKING and NK_INCLUDE_DEFAULT_FONT should add the default font configuration, but I'm still receiving this error.

`Assertion failed: (ctx->style.font && ctx->style.font->width && "if this triggers you forgot to add a font"), function nk_begin_titled, file nuklear.h, line 20199.`

My project is pretty much a skeleton, using the example on the github README.

Steps to reproduce:
1. Clone the project
2. Create main.cpp in the newly cloned Nuklear directory
3. Compile (`clang++ main.cpp -o main`)
4. Run main `./main`, see assertion failure

`main.cpp`

```
#define NK_IMPLEMENTATION
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT

#include "nuklear.h"

struct nk_context ctx;
enum {EASY, HARD};
static int op = EASY;
static float value = 0.6f;
static int i = 20;

int main(int argc, char* argv[]) {
  if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220),
               NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_CLOSABLE)) {
    /* fixed widget pixel width */
    nk_layout_row_static(&ctx, 30, 80, 1);
    if (nk_button_label(&ctx, "button")) {
      /* event handling */
    }

    /* fixed widget window ratio width */
    nk_layout_row_dynamic(&ctx, 30, 2);
    if (nk_option_label(&ctx, "easy", op == EASY)) op = EASY;
    if (nk_option_label(&ctx, "hard", op == HARD)) op = HARD;

    /* custom widget pixel width */
    nk_layout_row_begin(&ctx, NK_STATIC, 30, 2);
    {
      nk_layout_row_push(&ctx, 50);
      nk_label(&ctx, "Volume:", NK_TEXT_LEFT);
      nk_layout_row_push(&ctx, 110);
      nk_slider_float(&ctx, 0, &value, 1.0f, 0.1f);
    }
    nk_layout_row_end(&ctx);
  }
  nk_end(&ctx);
  return 0;
}
```

I think I'm just missing something simple, and could use a little guidance. Thanks!

**Comment by kothman** [comment]
Running Mac OS 11.7, on a 2014 Macbook air.

**Comment by kothman** [comment]
Looks like I forgot to include the call to nk_init_default, but it looks like the function expects an nk_user_font, so unsure where to go from here. Looking into the font documentation more closely.

**Comment by riri** [comment]
Font handling is not easy, because it provides a lot of possibilities, it's normal to have difficulties at the beginning.

If you use the default font of Nuklear, everything is automatic concerning the loading of the font. You just have to call `nk_init_default()` as you would for any font loading scheme. For the `nk_user_font` parameter, you just send a null argument, Nuklear will use its own default font then (this structure is needing when you want to control how the font is used) :
```c
struct nk_context ctx;
nk_init_default(&ctx, 0);
```

If you want to understand more how all this works, read the introduction comment about font handling in `nuklear.h` (currently at line 3795.

**Comment by kothman** [comment]
Thanks for your response! I'll do more research and testing 👍
