### ISSUE TITLE
Please update the version of stb_truetype.h and stb_rect_pack.h in nuklear.h

### ISSUE THREAD

**Issue by ronaaron** [Immediate-Mode-UI/Nuklear#51]
The versions are very old, and in particular a number of bugs in TTF handling have been fixed in more recent versions.

**Comment by dumblob** [comment]
Thanks for letting us know. There was a similar request and I think the goal was to automatically update them in each run of `paq.sh`/`paq.bat` (i.e. during the "amalgamation" process). PRs are welcome and because it sounds like an easy to review change, they'll be merged very quickly (couple of days probably).

**Comment by ronaaron** [comment]
I was going to push to a new branch, but I don't seem to be able to do  that.  So I'm attaching the modified 'src/nuklear_font.h'.

**NOTE**: There are two functions which in the current version take an nk_allocator, but which have no such thing in the code I merge; I do not understand all the ramifications of *not* having the allocator, it seems to work as-is on my Linux box.

The functions in question are part of the baker:

- nk_tt_PackFontRangesRenderIntoRects
- nk_tt_PackEnd


[nuklear_font.zip](https://github.com/Immediate-Mode-UI/Nuklear/files/4086136/nuklear_font.zip)

**Comment by ronaaron** [comment]
The code does crash on macOS, so apparently the allocator is needed. I was hoping it might be possible to allocate whatever's needed beforehand rather than piecemeal.  But I don't know the code, and am relying on you guys.

**Comment by ronaaron** [comment]
Still relying on you guys... any feedback on the need for the allocator?

**Comment by dumblob** [comment]
I'm still out of time to do reviews. But what caught my eye is that you can't submit a PR - that's weird. Could you please try again (step by step as [GitHub doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request ) says)? It would encourage others to look over your changes :wink:.

**Comment by ronaaron** [comment]
Pinging again, since I put a PR in just after your last comment.  Looking for assistance on that issue, since the ancient TTF support is hindering me.

**Comment by dumblob** [comment]
@Nielsbishere feel free to review the PR - I'd like to give you commit permission afterwards :wink:

**Comment by SairesArt** [comment]
@ronaaron Someone shares my pain <3
I have been bothered by the old stb_library versions myself. Many thanks for for the PR and the contribution!

**Comment by ronaaron** [comment]
Yeah; I hope it gets integrated (with appropriate changes) soon.

**Comment by dumblob** [comment]
stb_truetype update request appeared several times also in the old Nuklear repo. I think we should move away from making changes to stb_truetype once and forever. Could you @ronaaron change your [PR](https://github.com/Immediate-Mode-UI/Nuklear/pull/53 ) in a way, that there is separate `stb_truetype.h` taken 1:1 from the stb repo and then in `src_nuklear_font.c` there'll be just the Nuklear-specific stuff? It'll be also easier to review :wink: (and I think I'll review it despite my lack of time because of the high demand).

@SairesArt would you want to review the PR (or other PRs)? This would help the project a lot (I'd then give you commit permission :wink:).

**Comment by SairesArt** [comment]
> that there is separate `stb_truetype.h` taken 1:1 from the stb repo

That sounds like a good ~~quality of life~~ quality of code change for future updates, which ideally should have been done from the get go. So @ronaaron is unknowingly kicking off some important code refactoring :P
> 
> @SairesArt would you want to review the PR (or other PRs)? This would help the project a lot (I'd then give you commit permission wink).

I was very pleasantly surprised to find nuklear changing repos and being revived again, after some slumber during the past two years. Contributing to nuklear has been on my todo list for quite some time (GLFW OpenGL ES2 demo and ideally an option for SDF text rendering), but never came around to it... so I'll gladly take you up on that offer. Whilst I'm at it, I'll make a fresh new github account, message you this evening for the permissions and review me some PR's this weekend :]

**Comment by ronaaron** [comment]
So I just uploaded a modified version of my ttf branch, which separates both stb files. I had to also play a bit with the packer so that I could get the STB*IMPLEMENTATION if NK_IMPLEMENTATION is defined.  

I left two "TODO" comments in the code, where I am not sure what to do.

**Comment by FrostKiwi** [comment]
@SairesArt Here with my new Account to tackle all my Open Source responsibilities :]
@dumblob Although a bit late, I'd love to get commit rights and go through the backlog of PRs now.

**Comment by SairesArt** [comment]
> @SairesArt Here with my new Account

@FrostKiwi Quick proof of ownership via quote reply
Welp, so much for "this weekend". Life decided to head a couple more stuff my way, but now I can take on some PRs^^

**Comment by dumblob** [comment]
@FrostKiwi greetings and thanks for your interest. Could you please find the culprit for the last unsolved issue described in https://github.com/Immediate-Mode-UI/Nuklear/pull/53#discussion_r377141124 ? Then I'll merge the PR and you'll get the commit rights :wink:.

**Comment by dumblob** [comment]
I think this can be closed as the PR https://github.com/Immediate-Mode-UI/Nuklear/pull/53 got merged. Feel free to reopen if you feel so.
