### ISSUE TITLE
compile nuklear.h to lib 

### ISSUE THREAD

**Issue by rjopek** [Immediate-Mode-UI/Nuklear#510]
Hi, 

attempts to execute lib from nuklear.h with no success.
Maybe there is way to disable those assert macros altogether with a flag?
the case only applies to Windows 10.

it was talked about here:
https://github.com/Immediate-Mode-UI/Nuklear/issues/320

it looks odd to use -1 as an array index, as it instantly results in a buffer underrun.

**Comment by RobLoach** [comment]
To disable assert macros, define your own NK_ASSERT

```c
#define NK_ASSERT(expr) (void)(expr)
```
