### ISSUE TITLE
Possible Bug in nuclear_edit Clipboard Copy

### ISSUE THREAD

**Issue by jmwright** [Immediate-Mode-UI/Nuklear#514]
I was not able to find an issue for this. In nuclear_edit.c [here](https://github.com/Immediate-Mode-UI/Nuklear/blob/6322f53cb569bb989873ee8a1b71ae705b230708/src/nuklear_edit.c#L288), `clip->copy` is checked, but I think it should be checking the `copy` variable from a [few lines above](https://github.com/Immediate-Mode-UI/Nuklear/blob/6322f53cb569bb989873ee8a1b71ae705b230708/src/nuklear_edit.c#L275). This would be consistent with the way the `cut` variable is used [here](https://github.com/Immediate-Mode-UI/Nuklear/blob/6322f53cb569bb989873ee8a1b71ae705b230708/src/nuklear_edit.c#L290) (directly below the copy line) as well.

I can open a PR with the fix, but I wanted to make sure I wasn't missing something simple first.

**Comment by revolucas** [comment]
I believe it's intentional. If this was changed to `if (copy)` then cut functionality would break. It's not supposed to be if (copy) else if (cut). It should copy on both occasions, cut just has an extra step where it deletes the text in the edit box.

**Comment by jmwright** [comment]
Thanks
