### ISSUE TITLE
Link to the repo from the docs site

### ISSUE THREAD

**Issue by dustContributor** [Immediate-Mode-UI/Nuklear#515]
Hi! Sadly in google so far you still get vurtun's repository first when you google Nuklear. But one of the results is this nice site:

https://immediate-mode-ui.github.io/Nuklear/doc/index.html#

Which doesn't links anywhere to the repository, so to find the repository I had to google specifically for "immediate mode ui nuklear".  Something someone without knowledge of this fork will probably not do and end up back in vurtun's repository.

I'd suggest you add a big link to this repository on the docs at the very least in the About section right at the top, for easy access to newcomers. Maybe even specify that vurtun's repo is not maintained, that'd be good to know.

Thank you for your time.

**Comment by dumblob** [comment]
Oh, wow. We absolutely did not realize! Thanks a ton!

Would you make a PR?
