### ISSUE TITLE
UBSan trip in GLFW+OGL3 Backend

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [Immediate-Mode-UI/Nuklear#516]
When using the GLFW+OGL3 demo backend with UBSan tooling, `nk_glfw3_render` leads to the following message:
```
nuklear_glfw_gl3.h:297:20: runtime error: applying non-zero offset 240 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior nuklear_glfw_gl3.h:297:20
```
The line in question is here - which makes me think that the loop condition relies on a pseudo OOB?
![Screenshot 2022-11-22 at 21 44 13](https://user-images.githubusercontent.com/80696589/203427294-79de7bd3-e15e-44d0-8be0-952530c072d5.png)

This probably doesn't pose much of an actual functionality worry, but it's kind of annoying when libs can cause trips as then suppressions are needed etc.

If this could be fixed it would be swell, thanks!

**Comment by dumblob** [comment]
Sure, thanks for pointing it out. Could you make a PR? Thanks!
