### ISSUE TITLE
Converting examples/demos to CMake

### ISSUE THREAD

**Issue by learn-more** [Immediate-Mode-UI/Nuklear#524]
Would you be open to converting all Makefiles / batch files to CMake?
This would allow easier cross-platform testing / building.

Additionally, when you would agree on using CMake, how do you feel about using [vcpkg](https://vcpkg.io/) for package management?
This integrates with CMake, and can be used in Windows, Linux and Mac.
The recommended way is to use vcpkg as submodule, but this can also be done as manual checkout.

See [example runners](https://github.com/marketplace/actions/run-vcpkg#samples) for how build definitions could look like.

**Comment by Ryder17z** [comment]
if this actually gets made I really hope it does not follow the typical "cmake cult" creations.
9 times out of 10 the cmake config I find in any project has too many problems to even bother looking at them.

**Comment by dumblob** [comment]
There is some ongoing work on CMake stuff in https://github.com/Immediate-Mode-UI/Nuklear/pull/462 . We utterly need reviewers - feel free to jump at it and review! After (very) few comprehensive reviews we are immediately giving full admin commit rights (to increase [bus factor](https://en.wikipedia.org/wiki/Bus_factor )).

**Comment by RobLoach** [comment]
What dumblob said :+1:
