### ISSUE TITLE
Images fail to load in examples

### ISSUE THREAD

**Issue by fluentpwn** [Immediate-Mode-UI/Nuklear#528]
Building all of the examples(via `make all`), images fail to load. (`[SDL]: failed to load image:`)
Same happens in my code where I use the `icon_load` function from `extended.c`.

SDL/SDL2 libs are installed.

Sys. info(`inxi --system`):
```
System:
  Host: artix Kernel: 6.0.12-artix1-1 arch: x86_64 bits: 64 Desktop: dwm
    v: 6.4 Distro: Artix Linux
```

**Comment by RobLoach** [comment]
You may have to run them from the correct directory.

**Comment by fluentpwn** [comment]
> You may have to run them from the correct directory.

Oh, yep, works now! Thanks.

**Comment by fluentpwn** [comment]
One more problem: how to expand https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/glfw_opengl3 to load images? Just using the icon_load I get a seg.fault on `glGenerateMipmap(GL_TEXTURE_2D)`

**Comment by fluentpwn** [comment]
Nevermind, I guess that was a problem with my system somehow. (I installed another distro and it just works now?)
