### ISSUE TITLE
is there a certain feature?

### ISSUE THREAD

**Issue by pierce-c** [Immediate-Mode-UI/Nuklear#552]
does this library have a node or block or whatever that allows the developer to create like an array or 2d array that corresponds directly with the pixels on the screen? idk if this is specific enough but i want to know if theres a thing that maps directly to the screen the pixels without some interface, just like having a thing of pixels that i can write to the window with

**Comment by pierce-c** [comment]
also how do i install? i didn't see anything about that on the readme or the doc html

**Comment by dumblob** [comment]
Yes, you can have your arbitrary bitmap (image/picture) and just pass it to Nuklear as image and the Nuklear backend of your choice will draw it to the screen for you.

Regarding installation, note this is a header-only library and thus is not meant to be compiled as separate library and thus there is nothing like installation. Just copy `nuklear.h` to your code project folder and follow Nuklear documentation on how to `#include` it and you are done :wink:.
