### ISSUE TITLE
OpenGL Editor sample code

### ISSUE THREAD

**Issue by doctoryGlobal** [Immediate-Mode-UI/Nuklear#554]
Hello Team !
this is a such wonderful framework. 
I have been exploring the doc and find the sample OpenGl Editor. However this sample code can not be found. 
Please, is anyone could share the sample code ?

Thank you
![nuklear_opengl_editor](https://github.com/Immediate-Mode-UI/Nuklear/assets/4282976/e08cc97f-58ed-4492-a3e6-4e15ac681d33)

**Comment by dumblob** [comment]
I think this was some private SW @vurtun was writing himself and just took a screenshot and put it into the doc as a nice demonstration.

But feel free to build one yourself from the existing demos and backends - it should be pretty straightforward to add the few lines to show 3 cubes :wink:.
