### ISSUE TITLE
Demo bugs in "Overview": "Titlebar" checkbox has no effect and "Minimize" checkbox hides/shows both minimize button and titlebar

### ISSUE THREAD

**Issue by Ryder17z** [Immediate-Mode-UI/Nuklear#555]
![ColorPal-Generator_V0056y1afu](https://github.com/Immediate-Mode-UI/Nuklear/assets/2000703/10a7d6ad-73d5-464a-8b91-692b82d386f5)

**Comment by riri** [comment]
Yep, I suppose everyone knows this bug but nobody took time to fix it. That wouldn't be too long to fix (any PR welcome)

**Comment by riri** [comment]
Actually, so easy I just did it in #558 :)
