### ISSUE TITLE
How do you set "default text" in a text field?

### ISSUE THREAD

**Issue by Ryder17z** [Immediate-Mode-UI/Nuklear#557]
I'm unable to find a way to populate a text input field.

**Comment by RobLoach** [comment]
https://github.com/Immediate-Mode-UI/Nuklear/wiki/Text-Edit

**Comment by Ryder17z** [comment]
At the time of opening the issue, it either would not display the text or it made the input field read-only if I remember correctly.

I didn't note down behaviour or save the code as this was just frustrating me, instead I found it look better visually to just have the field empty and put the text in an nk_label.
