### ISSUE TITLE
Cannot avoid STB_RECT_PACK_IMPLEMENTATION / STB_TRUETYPE_IMPLEMENTATION

### ISSUE THREAD

**Issue by Gargaj** [Immediate-Mode-UI/Nuklear#566]
The `NK_INCLUDE_FONT_BAKING` macro enforces the implementation of the rectpack/truetype libraries:

```
#ifdef NK_INCLUDE_FONT_BAKING

#define STB_RECT_PACK_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
```

I have those implemented elsewhere in a project, so this is causing a multiple definition problem.

**Comment by RobLoach** [comment]
I'm not sure if this would completely fix the problem, as the headers are still included: https://github.com/Immediate-Mode-UI/Nuklear/pull/578
