### ISSUE TITLE
Knob widgets

### ISSUE THREAD

**Issue by theoparis** [Immediate-Mode-UI/Nuklear#567]
I would love to use nuklear over imgui but nuklear is unfortunately lacking knob/dial widgets. I have no idea how I would implement one myself.

I came across this issue but its on the old, deprecated repository with no progress: https://github.com/vurtun/nuklear/issues/841

**Comment by RobertAlbus** [comment]
I second this. Knobs would be a huge value-add for me.

**Comment by Ryder17z** [comment]
Part of the knob code would be fairly simple:
If hovering over the knob element, listen for input events: keyboard UP/DOWN and scrollwheel.

As for dragging, that's harder to implement, but is kinda necessary to have a functional knob.

**Comment by PROP65** [comment]
#669

**Comment by riri** [comment]
Closing this one as knobs exist with #669
