### ISSUE TITLE
GDI+ (gdip), Text Input Copy/Paste/Ctrl+A not working

### ISSUE THREAD

**Issue by nyaruku** [Immediate-Mode-UI/Nuklear#572]
![image](https://github.com/Immediate-Mode-UI/Nuklear/assets/38096703/5dddd27f-1a36-478c-bdea-450899e4e6f8)
So I'm working on an Application with Nuklear and i realised following things:
- Ctrl+C (copy) only works partially, when i paste into notepad.exe, it works, while pasting into windows search, it doesnt.
- Ctrl+V (paste) doesn't do anything as well as Ctrl+A (select entire text).
![image](https://github.com/Immediate-Mode-UI/Nuklear/assets/38096703/a9f31b78-a570-4182-b1d1-ed188ac607c1)

**Comment by a1ive** [comment]
https://github.com/Immediate-Mode-UI/Nuklear/blob/614abce05b9455849bbf1519b7f86e53c78b04ab/demo/gdip/nuklear_gdip.h#L789
=> `if (!IsClipboardFormatAvailable(CF_UNICODETEXT) || !OpenClipboard(NULL))`
It's working for me. (https://github.com/Immediate-Mode-UI/Nuklear/issues/126)

**Comment by nyaruku** [comment]
> https://github.com/Immediate-Mode-UI/Nuklear/blob/614abce05b9455849bbf1519b7f86e53c78b04ab/demo/gdip/nuklear_gdip.h#L789
> => `if (!IsClipboardFormatAvailable(CF_UNICODETEXT) || !OpenClipboard(NULL))`
> It's working for me. (https://github.com/Immediate-Mode-UI/Nuklear/issues/126)

maybe copy only, but for me ctrl+a and paste into the text input isn't working, and i also tried to switch to GDI which is very easy from GDI+, and GDI indeed works, but not gdi+, so I'll have to stick with that for now, gonna try to compare the gdi+ header with the gdi if i can find a fix.

**Comment by nyaruku** [comment]
Alright i fixed copy/paste by just using the code from the gdi header, now i have to fix the ctrl+a im pretty sure it has something to do with the key events, gonna do a PR once i fixed that too

**Comment by nyaruku** [comment]
![image](https://github.com/Immediate-Mode-UI/Nuklear/assets/38096703/aa46edd1-1cdd-4255-9a12-b1797dc3c8a9)
after comparing both headers, i realised that gdip header doesnt even have a switch statement to select all the text bruh

**Comment by nyaruku** [comment]
Fix is there, updated my PR: https://github.com/Immediate-Mode-UI/Nuklear/pull/576/commits/0435477a914dc4a58e3e80dd5301314757a67749
