### ISSUE TITLE
Three optimisation requests: 'window-moved?...

### ISSUE THREAD

**Issue by ronaaron** [Immediate-Mode-UI/Nuklear#61]
Three additional APIs can make things better for the programmer (and the UX):

- nk_was_window_moved  -- rather than storing the window bounds and comparing each render cycle, NK already knows when it moved a window.  A simple flag (zeroed after being checked) would be useful
- nk_was_window-resized -- same as above, but even more useful, since a lot of UX involves calculating bounds-- and if the window isn't resized, all that work can be eliminated
- nk_event_count -- not all the backends (GLFW, anyone?) tell you if events were processed or not. An optimisation can be to not render if no events were received. Since NK knows when events occur, it makes sense for it to return a simple count of events since the last query.

**Comment by dumblob** [comment]
I know I'm a bit late to the party, but I think these suggestions are not completely off - we just need someone to make a PR, so that we can evaluate the benefits in practice (I suppose embedded, mobile and web platforms would be the ones most interested in such changes).
