### ISSUE TITLE
Request: create example for showcasing integration with RGFW

### ISSUE THREAD

**Issue by quadroli** [Immediate-Mode-UI/Nuklear#615]
Helloo 👋 I'd like to request whether someone could make a demo using @colleagueRiley's [RGFW](https://github.com/ColleagueRiley/RGFW) it's piqued my interest.

**Comment by RobLoach** [comment]
Feel free to take a crack at implementing RGFW. Check out the rawfb demo for inspiration

**Comment by ColleagueRiley** [comment]
@quadroli  Feel free to move this issue to the RGFW repo. I may look into creating an example using Nuklear in the future.

**Comment by ColleagueRiley** [comment]
@quadroli 
In case you're still interested I made a RGFW backend for nuklear
https://github.com/ColleagueRiley/nuklear_rgfw

**Comment by quadroli** [comment]
@ColleagueRiley 
Very cool, thank you 🤛
