### ISSUE TITLE
Demo doesn't include code on how to display images without OpenGL.

### ISSUE THREAD

**Issue by malespiaut** [Immediate-Mode-UI/Nuklear#622]
Hello,

I was reading the demo code for the `sdl_renderer`, but when I looked for examples on how to display a `nk_image`, I've only founc examples that requires OpenGL.

The demo code should, in my humble opinion, have example that covers displaying images without the use of OpenGL.

Best regards.

**Comment by RobLoach** [comment]
Wiki has image examples for SDL https://github.com/Immediate-Mode-UI/Nuklear/wiki/SDL

Would like a common image example, perhaps handled via this pr https://github.com/Immediate-Mode-UI/Nuklear/pull/466
