### ISSUE TITLE
2 errors  

### ISSUE THREAD

**Issue by sevstels** [Immediate-Mode-UI/Nuklear#648]
nuklear.h(16730): error C2440: '=' : cannot convert from 'const nk_allocator *' to 'void *'
nuklear.h(16738): error C2664: 'stbtt_PackBegin' : cannot convert parameter 7 from 'const nk_allocator *' to 'void *'

fix
nuklear.h(16730):  font_info->userdata = (void*)alloc;
stbtt_PackBegin(&baker->spc, 0, (int)*width, (int)max_height, 0, 1, (void*)alloc);

**Comment by RobLoach** [comment]
@SnootierMoon Is this related to the recent change in #642 ?

**Comment by SnootierMoon** [comment]
> @SnootierMoon Is this related to the recent change in #642 ? Rebuilt with paq.sh and it has the fix: #649

Oh yeah, I got these same errors. I remember that I fixed it in my second commit, but I probably forgot to `git add nuklear.h` after running `paq.sh`. My bad.
