### ISSUE TITLE
9-slice/9-patch support for skinning

### ISSUE THREAD

**Issue by Michael-Kelley** [Immediate-Mode-UI/Nuklear#68]
I'm currently using nuklear and needed support for 9-slice textures for buttons, windows, etc. I have modified a local clone of nuklear to add the required features and am curious as to whether or not there is any interest in having these features pushed upstream. If so, I can make a PR.

**Comment by dumblob** [comment]
I'm not any more that reluctant to this functionality - how big is that change? I'd very much prefer to make this change an *addition*, i.e. fully backwards compatible.

**Comment by Michael-Kelley** [comment]
It's essentially a copy of nk_image.c for 9-slice images, an additional style function (nk_style_item_9slice), relevant additions to nk_style_item_type and nk_style_item_data, and modifications to control drawing functions to add support for 9-slice alongside image and color. It uses a separate function to draw and introduces no breaking changes.

**Comment by dumblob** [comment]
Which backends did you implement? Just make a PR and let's discuss it more technically to smoothen the potential sharper edges :wink: (don't forget to bump version, make changes to `src/*` and then run `src/paq.sh` or `src/paq.bat`).

**Comment by wheybags** [comment]
Just a note that I would be interested in using this for https://github.com/freeablo.
Especially if there was a mode to allow repeating the edge sections instead of stretching them.

**Comment by RobLoach** [comment]
I believe 9-slice has been implemented. I haven't used it, nor have a seen a demo of it though. Feel free to re-open if you'd like some clarification on it! :rocket: Was over at https://github.com/Immediate-Mode-UI/Nuklear/pull/304
