### ISSUE TITLE
Can't put combo box in a pop-up window

### ISSUE THREAD

**Issue by kamilzubair** [Immediate-Mode-UI/Nuklear#71]
If I have a combo box in a pop-up window, it will crash when I click on the combo box. The assertion is in the line NK_ASSERT(!(panel->type & NK_PANEL_SET_POPUP)); in the function nk_nonblock_begin (line 16912).
Is this the desired behavior? what other components can't be used in a pop-up window ?

**Comment by dumblob** [comment]
>Is this the desired behavior?

I'd believe so as popups are a bit of a hack - there are some pending PRs to solve this, so you might take a look at them and try if they solve also your issue.

>what other components can't be used in a pop-up window ?

Can't tell the full list, but this might help a bit:

```sh
$ grep -Er NK_ASSERT Nuklear/ | grep -E POPUP
Nuklear/nuklear.h:    NK_ASSERT(!(panel->type & NK_PANEL_SET_POPUP) && "popups are not allowed to have popups");
Nuklear/nuklear.h:    NK_ASSERT(!(panel->type & NK_PANEL_SET_POPUP));
Nuklear/nuklear.h:    NK_ASSERT(popup->layout->type & NK_PANEL_SET_POPUP);
Nuklear/nuklear.h:    NK_ASSERT(panel->type & NK_PANEL_SET_POPUP);
Nuklear/src/nuklear_contextual.c:    NK_ASSERT(panel->type & NK_PANEL_SET_POPUP);
Nuklear/src/nuklear_popup.c:    NK_ASSERT(!(panel->type & NK_PANEL_SET_POPUP) && "popups are not allowed to have popups");
Nuklear/src/nuklear_popup.c:    NK_ASSERT(!(panel->type & NK_PANEL_SET_POPUP));
Nuklear/src/nuklear_popup.c:    NK_ASSERT(popup->layout->type & NK_PANEL_SET_POPUP);
```

**Comment by kamilzubair** [comment]
Thanks for the info, I finally just show the window as a normal window instead of a popup
