### ISSUE TITLE
Documentation link no longer works

### ISSUE THREAD

**Issue by csstup** [Immediate-Mode-UI/Nuklear#730]
The doc link on the main README of the repo goes to https://immediate-mode-ui.github.io/Nuklear/doc/nuklear.html.   This is a 404 now.

**Comment by adrianboyko** [comment]
Captured by archive.org on Feb 8, 2024:
https://web.archive.org/web/20240208041722/https://immediate-mode-ui.github.io/Nuklear/doc/index.html

**Comment by riri** [comment]
It seems it is because of PR #722 merged, but no CI/DI workflow has been created (because doc is in ignore list now), hence the absence on github.io. @awschult002 could you have a look ?

**Comment by riri** [comment]
Fixed in merged PR #734
