### ISSUE TITLE
nk_xcb_init: no xcb window title

### ISSUE THREAD

**Issue by beatwise** [Immediate-Mode-UI/Nuklear#738]
nk_xcb_init doesn't set the window title.

This sets the title (see https://xcb.freedesktop.org/windowcontextandmanipulation/ ):

`	xcb_change_property(conn,
		XCB_PROP_MODE_REPLACE,
		window,
		XCB_ATOM_WM_NAME,
		XCB_ATOM_STRING,
		8,
		strlen(title),
		title);
`

**Comment by riri** [comment]
PR welcome if you already know how to fix it

**Comment by beatwise** [comment]
To fix it, simply add the code i wrote after **xcb_create_window**.
