### ISSUE TITLE
nuklear_xcb: no text input

### ISSUE THREAD

**Issue by beatwise** [Immediate-Mode-UI/Nuklear#741]
Demo's input boxes don't show any text when pressing keys:

**xcb_key_symbols_get_keysym** always returns 0. Probably, it's because _kp->state_ is not a valid argument for its third parameter "col".

**Comment by riri** [comment]
Would you make a PR about this?

**Comment by beatwise** [comment]
I have no fix for this. It's pretty involved: https://github.com/iplinux/xcb-util/blob/master/keysyms/keysyms.c#L110

There's an easier way: libxkbcommon - https://xkbcommon.org/doc/current/md_doc_2quick-guide.html
