### ISSUE TITLE
Proposed Change `nk_strto` and `nk_strtoi` 

### ISSUE THREAD

**Issue by rjopek** [Immediate-Mode-UI/Nuklear#743]
I suggest modifying the following two lines in nuklear.h to address type compatibility warnings with GCC:

```c
width = nk_strtoi(iter, &end);
precision = nk_strtoi(iter, &end);
```
Change them to:
```c
width = nk_strtoi(iter, (char**)&end);
precision = nk_strtoi(iter, (char**)&end);
```
This resolves the warning:
`passing argument 2 of 'nk_strtoi' from incompatible pointer type.`

The change ensures compatibility without altering the function signature of `nk_strtoi`.

**Comment by RobLoach** [comment]
I think this was fixed in https://github.com/Immediate-Mode-UI/Nuklear/pull/740 .
