### ISSUE TITLE
Backend: Direct3D 12

### ISSUE THREAD

**Issue by Hecklezz** [Immediate-Mode-UI/Nuklear#83]
I notice that nuklear hasn't had any development on a D3D12 implementation/example and was wondering if this will be worked on in the near future or not?
ImGUI has been working on a D3D12 Rendering implementation since early 2018 and it is currently in a pretty good state and works well. 

It would be nice to see Nuklear also be able to render with D3D12.

**Comment by dumblob** [comment]
It should be actually really easy to port/use the ImGUI backend as Nuklear backend. Dare to make a PR?

**Comment by ddrsilva** [comment]
I started yesterday porting ImGUI backend to Nuklear and is almost done, just need to fix some issues

**Comment by dumblob** [comment]
Sounds promising @ddrsilva , thanks. Before submitting the PR, please take a look at [what'll reviewers try to look for](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide ) among other things.

**Comment by ddrsilva** [comment]
So this is my current state on the Dx12 implementation,
https://i.imgur.com/HbhdXmp.gifv

 im having this issue, I belive is on the " fill converting configuration" of Nuklear Just need to play around a bit more to see what is really going  on, but should be done really soon :D
