### ISSUE TITLE
Tree list x coordinate bug

### ISSUE THREAD

**Issue by Shiro-github** [Immediate-Mode-UI/Nuklear#85]
After around this push the x coordinate is getting offset when more than one tree list is open. (#2) 

Before:
![NVIDIA_Share_w3wpMqShnk](https://user-images.githubusercontent.com/51446317/76779138-2a010580-67ab-11ea-91f0-361491207b2f.png)

After:
![demo_OBn6tUech6](https://user-images.githubusercontent.com/51446317/76779199-40a75c80-67ab-11ea-854b-593d6be16751.png)

**Comment by dumblob** [comment]
Does this commit https://github.com/Immediate-Mode-UI/Nuklear/commit/75c71790f30c3d69ccfd6e33ac7c7764acfcfd0a solve it for you (i.e. do you use the latest `nuklear.h` from the master branch)?

**Comment by Shiro-github** [comment]
No, it's still the same, and yes i used the latest branch.

**Comment by dumblob** [comment]
@Hejsil do you still have some bits of it in your head to take a look?

**Comment by exchg** [comment]
Seems that the problem with offset restoration at this point:

```
void nk_tree_state_pop(struct nk_context *ctx)
{
    struct nk_window *win = 0;
    struct nk_panel *layout = 0;

    assert(ctx);
    assert(ctx->current);
    assert(ctx->current->layout);
    if (!current_layout_exist(ctx))
        return;

    win = ctx->current;
    layout = win->layout;

    /* Look here !!!  */
    /* layout->at_x -= ctx->style.tab.indent + ctx->style.window.padding.x; */
    layout->at_x -= ctx->style.tab.indent + (float)*layout->offset_x;

    layout->bounds.w += ctx->style.tab.indent + ctx->style.window.padding.x;
    assert(layout->row.tree_depth);
    layout->row.tree_depth--;
}
```

**Comment by Hejsil** [comment]
Hmm. It seems that #2 was not as trivial of a fix as I thought it would be. I'm on vacation right now, so can't take a look at it until Friday maybe.

**Comment by dumblob** [comment]
@Hejsil enjoy your vacation until then!

**Comment by Hejsil** [comment]
@exchg I've look into this a bit, and it seems you where strait on the mark. The `nk_tree_state_pop` function restores the layout, which means it should revert the layout and bounds changes that `nk_tree_state_base` setup, which it wasn't doing correctly.

Do you want to make a pull request so you get credit for this fix, or should I just do it?

**Comment by exchg** [comment]
@Hejsil Great! Do it please.
