### ISSUE TITLE
error C2039: 'n': is not a member of 'nk_font_config'

### ISSUE THREAD

**Issue by riderv** [Immediate-Mode-UI/Nuklear#92]
} while ((i = i->n) != iter);
...
struct nk_font_config {
    struct nk_font_config *next;

Вообще что-ли простыми тестами код не покрыт?

**Comment by dumblob** [comment]
Could you please edit your post and write it in English? Don't worry if you don't master English very well - we just want to keep this tracker international.

**Comment by RobLoach** [comment]
All warnings have been cleaned up since last year. This should be okay now.
