### ISSUE TITLE
Compile error MSYS2 x64 GCC 9.3.0 Win10 -1 sized array

### ISSUE THREAD

**Issue by saidwho12** [Immediate-Mode-UI/Nuklear#93]
Anyone know why this may be happening? I only #define NK_IMPLEMENTATION and include "nuklear.h" in main.c

C:/Users/Said/source/repos/EFTR/src/nuklear.h:291:61: error: size of array '_dummy_array422' is negative
  291 |   #define NK_STATIC_ASSERT(exp) typedef char NK_UNIQUE_NAME(_dummy_array)[(exp)?1:-1]

**Comment by dumblob** [comment]
Which flags do you use for compilation? Could you post full source code (maybe there is something fishy with other includes or alike)? Have you tried to compile stuff in `demo/` and `example/`?

**Comment by saidwho12** [comment]
Sorry, I fixed it somehow and I don't remember how, thanks still

**Comment by lockie** [comment]
I've stumbled upon the same problem with mingw-w64's GCC 8.1.0, and it looks like it was fixed by adding 
```c
#define NK_INCLUDE_FIXED_TYPES
```

**Comment by dumblob** [comment]
Thanks! Closing then.
