### ISSUE TITLE
OS window "tearing" on resize

### ISSUE THREAD

**Issue by ronaaron** [Immediate-Mode-UI/Nuklear#96]
What I mean is that the display 'freezes' in an odd manner when you resize a system window.  For example, take the SDL2 GL3 demo and add "SDL_WINDOW_RESIZABLE" to the SDL_CreateWindow() call so you can resize the OS window.

You'll notice the Nuklear window deforms when you resize the OS window.  This happens on all platforms I've tested on.

**Comment by dumblob** [comment]
>This happens on all platforms I've tested on.

Just for completeness, could you please list them, so that anybody can better reproduce?

**Comment by ronaaron** [comment]
macOS (10.14.6), Linux (Mint, 19.3), Windows 10

**Comment by dumblob** [comment]
On each platform which backends did you use to test it?

**Comment by ronaaron** [comment]
SDL2

**Comment by dumblob** [comment]
Which of these: `sdl_opengl2` `sdl_opengl3` `sdl_opengles2`?

**Comment by ronaaron** [comment]
sdl_opengl3, which is what I meant in the first post when I said "SDL2 GL3".  I don't think that's the difference, because I saw similar behavior e.g. with x11_gl3 back when.

**Comment by ronaaron** [comment]
It seems to actually be an SDL issue.  When the user resizes a window, the resize event isn't actually issued until the user lets go of the mouse.
