### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ninijo** [Immediate-Mode-UI/Nuklear#97]
Memory usage, keeps rising up in chunks of atleast ~20MB on Windows 7, on Windows 10 doesn't seem to be an issue...

I thought this might've been an issue with nuklear_glfw_gl3.h, but it happens also with nuklear_glfw_gl2.h, so I know that it's most-likely an issue with nuklear.h itself.

The program starts at 10MB memory usage, then climbs all the way up to ~151MB!

**Comment by dumblob** [comment]
This issue is not known to me. Could you make a wrapper around `malloc()` and `free()` to count how many bytes have been requested by Nuklear and how many freed? Or alternatively just run your app with *valgrind* (i.e. on Linux).

If that won't shed some light in the situation, could you provide more information (app source, compiler type & version, compiler flags used for compilation, your exact system version and used libraries version - e.g. GL libs, etc.)?

**Comment by ronaaron** [comment]
A data point: with SDL2 backend  on macOS don't see this issue; however, when I resize the SDL window the memory usage goes up several MB and levels off.

**Comment by saidwho12** [comment]
> This issue is not known to me. Could you make a wrapper around `malloc()` and `free()` to count how many bytes have been requested by Nuklear and how many freed? Or alternatively just run your app with _valgrind_ (i.e. on Linux).
> 
> If that won't shed some light in the situation, could you provide more information (app source, compiler type & version, compiler flags used for compilation, your exact system version and used libraries version - e.g. GL libs, etc.)?

I will, but currently the application has other issues and it has to stay private for some reasons, but I can for sure do a test with `malloc()` and `free()`. Can you tell me how I might do that? The application dependencies which are important are `npcap`, `pthread`, `glad`, `GL`, `glfw3` and my own library `glm-c.`

**Comment by dumblob** [comment]
>Can you tell me how I might do that?

Just write the wrappers and then define
```c
NK_LIB void* nk_malloc(nk_handle unused, void *old,nk_size size);
NK_LIB void nk_mfree(nk_handle unused, void *ptr);
```
while ensuring `NK_INCLUDE_DEFAULT_ALLOCATOR` is not defined. That everything before
```c
#define NK_IMPLEMENTATION
#include "nuklear.h"
```

For caveats please see the built-in documentation of flags (line 94 in `nuklear.h`). It also seems you're using threads, so make sure your `malloc()` and `free()` wrappers  are either thread safe or ensure nuklear stuff is always called from the same thread.

**Comment by saidwho12** [comment]
Is there a way to get the size of the freed block? Or should I only count the number of times both get called?

**Comment by saidwho12** [comment]
The values for nk_malloc() and nk_mfree() allocation count is the same, yet on my friend's windows 7 machine the memory grows indefinitely as if free() isn't doing anything and it grows ~200MB in like 5 minutes, and for me stays at ~20MB. Idk if it's Nuklear now, it could be free() that has issues on his system, or the OpenGL driver itself...

**Comment by saidwho12** [comment]
Could it be the nuklear_glfw_gl3.h file doing it? That uses malloc() and free() rather straight from stdlib.h.

**Comment by dumblob** [comment]
The advantage of Nuklear is, that it's itself still short and readable enough and especially the backends which are really short - so I'd encourage you to take a look yourself whether there are some alien allocations. It might also be, that the graphics driver on Windows does some weird stuff with these GL backends (I can imagine, that using shaders might mean the driver preallocates an excessive amount of memory etc.).

**Comment by ZaneA** [comment]
I've been struggling to find this one for a while as well, it seems that the demos don't free some buffers, and there is a `cmd_count` in `nk_draw_list` that is growing over time without being reset and causing reallocs. I noticed this while looking at the inline documentation for `NK_INCLUDE_VERTEX_BUFFER_OUTPUT` and noticed the extra `nk_buffer_free` calls in there.

For example in `demo/nuklear_glfw_gl3.h` around line 276:

```
            /* setup buffers to load vertices and elements */
            nk_buffer_init_fixed(&vbuf, vertices, (size_t)max_vertex_buffer);
            nk_buffer_init_fixed(&ebuf, elements, (size_t)max_element_buffer);
            nk_convert(&glfw.ctx, &dev->cmds, &vbuf, &ebuf, &config);
        }
        glUnmapBuffer(GL_ARRAY_BUFFER);
        glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER);

        /* iterate over and execute each draw command */
        nk_draw_foreach(cmd, &glfw.ctx, &dev->cmds)
        { ... }
        nk_clear(&glfw.ctx);
    }
```

should look something like this:

```
            /* setup buffers to load vertices and elements */
            nk_buffer_init_fixed(&vbuf, vertices, (size_t)max_vertex_buffer);
            nk_buffer_init_fixed(&ebuf, elements, (size_t)max_element_buffer);
            nk_convert(&glfw.ctx, &dev->cmds, &vbuf, &ebuf, &config);
            nk_buffer_free(&vbuf); // <--- this line
            nk_buffer_free(&ebuf); // <--- this line
        }
        glUnmapBuffer(GL_ARRAY_BUFFER);
        glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER);

        /* iterate over and execute each draw command */
        nk_draw_foreach(cmd, &glfw.ctx, &dev->cmds)
        { ... }
        nk_clear(&glfw.ctx);
        nk_buffer_free(&dev->cmds); // <--- this line
        nk_buffer_init_fixed(&dev->cmds, dev->cmds_buffer, (nk_size)MAX_COMMANDS); // <--- this line
    }
```

I also use `nk_buffer_init_fixed` here to reset the cmds structure and did the same to initialise it on line 129.

**Comment by dumblob** [comment]
Hm, calling `nk_buffer_free()` doesn't sound like something one would want to do for every frame. Maybe we should reconsider what everything `nk_clear()` does.

@Hejsil thoughts?

**Comment by Hejsil** [comment]
Not to familiar enough with what nuklear sets up and tears down in each frame to be of much help. Though, I do agree that `nk_buffer_free` on each frame seems like code smell and indicates there are some bufferes that should be reused.

**Comment by ZaneA** [comment]
I simplified the above changes a bit further by moving the cmds `nk_buffer` and a bit of scratch space onto the stack in the glfw render function and calling `nk_buffer_init_fixed` each frame (like is done with the mapped vertex/element buffers). Then the `nk_buffer_free` are no longer needed here, I agree that (de)allocating here isn't a good idea if not using fixed buffers :+1:. Maybe calling `nk_buffer_clear` around this point on a longer lived buffer would be better...

**Comment by dumblob** [comment]
@ZaneA could you make a PR with the changes you made? We're trying to get such improvement merged [as soon as possible](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide ).

**Comment by ZaneA** [comment]
@saidwho12 did the `nk_buffer_clear` patch solve this issue for you?

**Comment by saidwho12** [comment]
@ZaneA Yeah but I still haven't tested it on my friend's machine, but on my computer it's fine.

**Comment by RobLoach** [comment]
Going to assume this memory leak has been fixed. Thanks a lot, all!
